'use strict';
goog.provide('Blockly.Arduino.pins');
goog.require('Blockly.Arduino');
Blockly.Arduino.pins_digital = function() {
  var code = this.getFieldValue('PIN');
  return [code, Blockly.Arduino.ORDER_ATOMIC];
};
Blockly.Arduino.pins_button=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_analog=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_pwm=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_dac = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_touch = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_interrupt=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_serial=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_builtinimg=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_imglist=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_playlist=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_axis=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_exlcdh = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_exlcdv = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_brightness=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_tone_notes = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_radio_power = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_radio_datarate = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_one_more = Blockly.Arduino.pins_digital;
//Blockly.Arduino.serial_select = Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_MOSI=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_MISO=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_SCK=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_scl=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_sda=Blockly.Arduino.pins_digital;
Blockly.Arduino.brightness=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_tx=Blockly.Arduino.pins_digital;
Blockly.Arduino.CHANNEL=Blockly.Arduino.pins_digital;
Blockly.Arduino.PWM_RESOLUTION=Blockly.Arduino.pins_digital;
Blockly.Arduino.OCTAVE=Blockly.Arduino.pins_digital;
Blockly.Arduino.TONE_NOTE=Blockly.Arduino.pins_digital;
Blockly.Arduino.pins_digitalWrite=Blockly.Arduino.pins_digital;