import * as Blockly from 'blockly/core';
import { Profile } from 'mixly';

import {
    PythonVariablesBlocks,
    PythonControlBlocks,
    PythonMathBlocks,
    PythonTextBlocks,
    PythonListsBlocks,
    PythonDictsBlocks,
    PythonLogicBlocks,
    PythonStorageBlocks,
    PythonProceduresBlocks,
    PythonTupleBlocks,
    PythonSetBlocks,
    PythonHtmlBlocks,
    PythonUtilityBlocks,
    PythonVariablesGenerators,
    PythonControlGenerators,
    PythonMathGenerators,
    PythonTextGenerators,
    PythonListsGenerators,
    PythonDictsGenerators,
    PythonLogicGenerators,
    PythonStorageGenerators,
    PythonProceduresGenerators,
    PythonTupleGenerators,
    PythonSetGenerators,
    PythonHtmlGenerators,
    PythonUtilityGenerators,
    Procedures,
    Variables,
    Python
} from '@mixly/python';

import {
    MicroPythonActuatorExternBlocks,
    MicroPythonActuatorOnBoardBlocks,
    MicroPythonAISensorBlocks,
    MicroPythonAIBlocks,
    MicroPythonBlynkBlocks,
    MicroPythonCommunicateBlocks,
    MicroPythonDisplayExternBlocks,
    MicroPythonDisplayOnBoardBlocks,
    MicroPythonFactoryBlocks,
    MicroPythonInputBlocks,
    MicroPythonIotBlocks,
    MicroPythonNetworkBlocks,
    MicroPythonNovaG1Blocks,
    MicroPythonPeG1Blocks,
    MicroPythonSensorExternBlocks,
    MicroPythonSensorOnBoardBlocks,
    MicroPythonSerialBlocks,
    MicroPythonSystemBlocks,
    MicroPythonWeatherBlocks,
    MicroPythonActuatorExternGenerators,
    MicroPythonActuatorOnBoardGenerators,
    MicroPythonAISensorGenerators,
    MicroPythonAIGenerators,
    MicroPythonBlynkGenerators,
    MicroPythonCommunicateGenerators,
    MicroPythonDisplayExternGenerators,
    MicroPythonDisplayOnBoardGenerators,
    MicroPythonFactoryGenerators,
    MicroPythonInputGenerators,
    MicroPythonIotGenerators,
    MicroPythonNetworkGenerators,
    MicroPythonNovaG1Generators,
    MicroPythonPeG1Generators,
    MicroPythonSensorExternGenerators,
    MicroPythonSensorOnBoardGenerators,
    MicroPythonSerialGenerators,
    MicroPythonSystemGenerators,
    MicroPythonWeatherGenerators
} from '@mixly/micropython';

import {
    MicropythonESP32S3Pins,
    MicropythonESP32S3InoutBlocks,
    MicropythonESP32S3PinsBlocks,
    MicropythonESP32S3SANTG2Blocks,
    MicropythonESP32S3InoutGenerators,
    MicropythonESP32S3PinsGenerators,
    MicropythonESP32S3SANTG2Generators
} from './';

import './css/color_esp32s2_mixgoce.css';

Object.assign(Blockly.Variables, Variables);
Object.assign(Blockly.Procedures, Procedures);
Blockly.Python = Python;
Blockly.generator = Python;

Profile.default = {};
Object.assign(Profile, MicropythonESP32S3Pins);
Object.assign(Profile.default, MicropythonESP32S3Pins['MixGo CE']);

Object.assign(
    Blockly.Blocks,
    PythonVariablesBlocks,
    PythonControlBlocks,
    PythonMathBlocks,
    PythonTextBlocks,
    PythonListsBlocks,
    PythonDictsBlocks,
    PythonLogicBlocks,
    PythonStorageBlocks,
    PythonProceduresBlocks,
    PythonTupleBlocks,
    PythonSetBlocks,
    PythonHtmlBlocks,
    PythonUtilityBlocks,
    MicroPythonInputBlocks,
    MicroPythonSystemBlocks,
    MicroPythonSerialBlocks,
    MicroPythonCommunicateBlocks,
    MicroPythonIotBlocks,
    MicroPythonWeatherBlocks,
    MicroPythonAISensorBlocks,
    MicroPythonSensorOnBoardBlocks,
    MicroPythonSensorExternBlocks,
    MicroPythonPeG1Blocks,
    MicroPythonNetworkBlocks,
    MicroPythonAIBlocks,
    MicroPythonActuatorOnBoardBlocks,
    MicroPythonActuatorExternBlocks,
    MicroPythonDisplayOnBoardBlocks,
    MicroPythonDisplayExternBlocks,
    MicroPythonFactoryBlocks,
    MicroPythonBlynkBlocks,
    MicroPythonNovaG1Blocks,
    MicropythonESP32S3InoutBlocks,
    MicropythonESP32S3PinsBlocks,
    MicropythonESP32S3SANTG2Blocks
);

Object.assign(
    Blockly.Python.forBlock,
    PythonVariablesGenerators,
    PythonControlGenerators,
    PythonMathGenerators,
    PythonTextGenerators,
    PythonListsGenerators,
    PythonDictsGenerators,
    PythonLogicGenerators,
    PythonStorageGenerators,
    PythonProceduresGenerators,
    PythonTupleGenerators,
    PythonSetGenerators,
    PythonHtmlGenerators,
    PythonUtilityGenerators,
    MicroPythonInputGenerators,
    MicroPythonSystemGenerators,
    MicroPythonSerialGenerators,
    MicroPythonCommunicateGenerators,
    MicroPythonIotGenerators,
    MicroPythonWeatherGenerators,
    MicroPythonAISensorGenerators,
    MicroPythonSensorOnBoardGenerators,
    MicroPythonSensorExternGenerators,
    MicroPythonPeG1Generators,
    MicroPythonNetworkGenerators,
    MicroPythonAIGenerators,
    MicroPythonActuatorOnBoardGenerators,
    MicroPythonActuatorExternGenerators,
    MicroPythonDisplayOnBoardGenerators,
    MicroPythonDisplayExternGenerators,
    MicroPythonFactoryGenerators,
    MicroPythonBlynkGenerators,
    MicroPythonNovaG1Generators,
    MicropythonESP32S3InoutGenerators,
    MicropythonESP32S3PinsGenerators,
    MicropythonESP32S3SANTG2Generators
);