import * as Blockly from 'blockly/core';
import { Profile } from 'mixly';

import {
    PythonVariablesBlocks,
    PythonControlBlocks,
    PythonMathBlocks,
    PythonTextBlocks,
    PythonListsBlocks,
    PythonDictsBlocks,
    PythonLogicBlocks,
    PythonStorageBlocks,
    PythonProceduresBlocks,
    PythonTupleBlocks,
    PythonSetBlocks,
    PythonHtmlBlocks,
    PythonUtilityBlocks,
    PythonVariablesGenerators,
    PythonControlGenerators,
    PythonMathGenerators,
    PythonTextGenerators,
    PythonListsGenerators,
    PythonDictsGenerators,
    PythonLogicGenerators,
    PythonStorageGenerators,
    PythonProceduresGenerators,
    PythonTupleGenerators,
    PythonSetGenerators,
    PythonHtmlGenerators,
    PythonUtilityGenerators,
    Procedures,
    Variables,
    Python
} from '@mixly/python';

import {
    MicroPythonActuatorBlocks,
    MicroPythonBlynkBlocks,
    MicroPythonDisplayBlocks,
    MicroPythonIotBlocks,
    MicroPythonActuatorGenerators,
    MicroPythonBlynkGenerators,
    MicroPythonDisplayGenerators,
    MicroPythonIotGenerators
} from '@mixly/micropython';

import {
    MicropythonK210MixgoAIPins,
    MicropythonK210MixgoAIActuatorBlocks,
    MicropythonK210MixgoAIAIBlocks,
    MicropythonK210MixgoAIAVBlocks,
    MicropythonK210MixgoAICameraBlocks,
    MicropythonK210MixgoAICommunicateBlocks,
    MicropythonK210MixgoAIDisplayBlocks,
    MicropythonK210MixgoAIFactoryBlocks,
    MicropythonK210MixgoAIHearBlocks,
    MicropythonK210MixgoAIImageBlocks,
    MicropythonK210MixgoAIInoutBlocks,
    MicropythonK210MixgoAIIotBlocks,
    MicropythonK210MixgoAIMathBlocks,
    MicropythonK210MixgoAINesBlocks,
    MicropythonK210MixgoAINetworkBlocks,
    MicropythonK210MixgoAIPinsBlocks,
    MicropythonK210MixgoAISensorBlocks,
    MicropythonK210MixgoAISerialBlocks,
    MicropythonK210MixgoAISystemBlocks,
    MicropythonK210MixgoAIUpdataBlocks,
    MicropythonK210MixgoAIActuatorGenerators,
    MicropythonK210MixgoAIAIGenerators,
    MicropythonK210MixgoAIAVGenerators,
    MicropythonK210MixgoAICameraGenerators,
    MicropythonK210MixgoAICommunicateGenerators,
    MicropythonK210MixgoAIDisplayGenerators,
    MicropythonK210MixgoAIFactoryGenerators,
    MicropythonK210MixgoAIHearGenerators,
    MicropythonK210MixgoAIImageGenerators,
    MicropythonK210MixgoAIInoutGenerators,
    MicropythonK210MixgoAIIotGenerators,
    MicropythonK210MixgoAIMathGenerators,
    MicropythonK210MixgoAINesGenerators,
    MicropythonK210MixgoAINetworkGenerators,
    MicropythonK210MixgoAIPinsGenerators,
    MicropythonK210MixgoAISensorGenerators,
    MicropythonK210MixgoAISerialGenerators,
    MicropythonK210MixgoAISystemGenerators,
    MicropythonK210MixgoAIUpdataGenerators
} from './';

import './css/color_k210_mixgoai.css';

Object.assign(Blockly.Variables, Variables);
Object.assign(Blockly.Procedures, Procedures);
Blockly.Python = Python;
Blockly.generator = Python;

Profile.default = {};
Object.assign(Profile, MicropythonK210MixgoAIPins);
Object.assign(Profile.default, MicropythonK210MixgoAIPins['k210']);

Object.assign(
    Blockly.Blocks,
    PythonVariablesBlocks,
    PythonControlBlocks,
    PythonMathBlocks,
    PythonTextBlocks,
    PythonListsBlocks,
    PythonDictsBlocks,
    PythonLogicBlocks,
    PythonStorageBlocks,
    PythonProceduresBlocks,
    PythonTupleBlocks,
    PythonSetBlocks,
    PythonHtmlBlocks,
    PythonUtilityBlocks,
    MicroPythonIotBlocks,
    MicroPythonDisplayBlocks,
    MicroPythonBlynkBlocks,
    MicroPythonActuatorBlocks,
    MicropythonK210MixgoAIActuatorBlocks,
    MicropythonK210MixgoAIAIBlocks,
    MicropythonK210MixgoAIAVBlocks,
    MicropythonK210MixgoAICameraBlocks,
    MicropythonK210MixgoAICommunicateBlocks,
    MicropythonK210MixgoAIDisplayBlocks,
    MicropythonK210MixgoAIFactoryBlocks,
    MicropythonK210MixgoAIHearBlocks,
    MicropythonK210MixgoAIImageBlocks,
    MicropythonK210MixgoAIInoutBlocks,
    MicropythonK210MixgoAIIotBlocks,
    MicropythonK210MixgoAIMathBlocks,
    MicropythonK210MixgoAINesBlocks,
    MicropythonK210MixgoAINetworkBlocks,
    MicropythonK210MixgoAIPinsBlocks,
    MicropythonK210MixgoAISensorBlocks,
    MicropythonK210MixgoAISerialBlocks,
    MicropythonK210MixgoAISystemBlocks,
    MicropythonK210MixgoAIUpdataBlocks
);

Object.assign(
    Blockly.Python.forBlock,
    PythonVariablesGenerators,
    PythonControlGenerators,
    PythonMathGenerators,
    PythonTextGenerators,
    PythonListsGenerators,
    PythonDictsGenerators,
    PythonLogicGenerators,
    PythonStorageGenerators,
    PythonProceduresGenerators,
    PythonTupleGenerators,
    PythonSetGenerators,
    PythonHtmlGenerators,
    PythonUtilityGenerators,
    MicroPythonIotGenerators,
    MicroPythonDisplayGenerators,
    MicroPythonBlynkGenerators,
    MicroPythonActuatorGenerators,
    MicropythonK210MixgoAIActuatorGenerators,
    MicropythonK210MixgoAIAIGenerators,
    MicropythonK210MixgoAIAVGenerators,
    MicropythonK210MixgoAICameraGenerators,
    MicropythonK210MixgoAICommunicateGenerators,
    MicropythonK210MixgoAIDisplayGenerators,
    MicropythonK210MixgoAIFactoryGenerators,
    MicropythonK210MixgoAIHearGenerators,
    MicropythonK210MixgoAIImageGenerators,
    MicropythonK210MixgoAIInoutGenerators,
    MicropythonK210MixgoAIIotGenerators,
    MicropythonK210MixgoAIMathGenerators,
    MicropythonK210MixgoAINesGenerators,
    MicropythonK210MixgoAINetworkGenerators,
    MicropythonK210MixgoAIPinsGenerators,
    MicropythonK210MixgoAISensorGenerators,
    MicropythonK210MixgoAISerialGenerators,
    MicropythonK210MixgoAISystemGenerators,
    MicropythonK210MixgoAIUpdataGenerators
);