// This file was automatically generated.  Do not modify.
'use strict';

goog.provide('Blockly.Msg.mg');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "ᠲᠠᠶᠢᠯᠪᠤᠷᠢ";
Blockly.Msg.AUTH = "请授权这个应用程序以保存您的作品并共享。";
Blockly.Msg.CHANGE_VALUE_TITLE = "更改值：";
Blockly.Msg.CHAT = "通过在此框输入与您的合作者沟通！";
Blockly.Msg.CLEAN_UP = "清理块";
Blockly.Msg.COLLAPSE_ALL = "折叠块";
Blockly.Msg.COLLAPSE_BLOCK = "折叠块";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = " ᠥᠩᠭᠡ1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "颜色2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "用一个给定的比率(0.0-1.0)混合两种颜色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/颜色";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "从调色板中选择一种颜色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "随机颜色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "随机选择一种颜色。";
Blockly.Msg.COLOUR_RGB_BLUE = "蓝色";
Blockly.Msg.COLOUR_RGB_GREEN = "绿色";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "红色";
Blockly.Msg.COLOUR_RGB_TITLE = "颜色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "通过指定红色、绿色和蓝色的量创建一种颜色。所有的值必须介于0和100之间。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "中断循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "继续下一次循环";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "中断包含它的循环。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳过这个循环的剩余部分，并继续下一次迭代。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告：此块仅可用于在一个循环内。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each用于每个块";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "在数组中";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "为每个项目";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍历每个数组中的项目，将变量“%1”设定到该项中，然后执行某些语句。";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO = "from %1 to %2";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "从范围 %1 到 %2 每隔 %3";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "使用";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "从起始数到结尾数中取出变量“%1”的值，按指定的间隔，执行指定的块。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "在if语句块中增加一个条件。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "添加一个最终的，包括所有情况的节到if块中。";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "增加、删除或重新排列各节来重新配置“if”块。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否则";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否则如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "如果值为真，执行一些语句。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "如果值为真，则执行语句的第一块；否则，则执行语句的第二块。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一个值为真，则执行语句的第一个块；否则，如果第二个值为真，则执行语句的第二块。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一个值为真，则执行语句的第一块；否则，如果第二个值为真，则执行语句的第二块；如果没有值为真，则执行语句的最后一块。";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For回圈";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "执行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重复 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "重复";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "次";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次执行一些语句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重复直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重复当";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "只要值为假，执行一些语句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "只要值为真，执行一些语句。";
Blockly.Msg.DELETE_BLOCK = "删除块";
Blockly.Msg.DELETE_X_BLOCKS = "删除 %1 块";
Blockly.Msg.DISABLE_BLOCK = "禁用块";
Blockly.Msg.DUPLICATE_BLOCK = "复制";
Blockly.Msg.ENABLE_BLOCK = "启用块";
Blockly.Msg.EXPAND_ALL = "展开块";
Blockly.Msg.EXPAND_BLOCK = "展开块";
Blockly.Msg.EXTERNAL_INPUTS = "外部输入";
Blockly.Msg.HELP = "帮助";
Blockly.Msg.INLINE_INPUTS = "单行输入";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://en.wikipedia.org/wiki/Linked_list#Empty_lists";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "初始化为空数组";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一个数组，长度为 0，不包含任何数据记录";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "数组";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "增加、删除或重新排列各部分以此重新配置这个数组块。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "初始化数组为";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "将一个项添加到数组中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一个具有任意数量项目的数组。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒数第#";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "获得";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出并移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最后";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "随机";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "空白";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回数组中的第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在数组中的指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在数组中的指定位置的项。#1是第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回数组中的最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "随机返回数组中的一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除并返回数组中的第一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除并返回数组中的指定位置的项。#1 是最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除并返回数组中的指定位置的项。#1 是第一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除并返回数组中的最后一个项目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除并返回数组中的一个随机项目中。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除数组中的第一项";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "删除在数组中的指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在数组中的指定位置的项。#1 是第一项。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除数组中的最后一项";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "删除数组中的一个随机的项。";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到倒数第#";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到#";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到最后";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "从头获得子数组";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "从倒数#取得子数组";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "从#取得子数组";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "空白";
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "复制数组中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出第一个项出现";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出最后一个项出现";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在数组中的第一/最后一个匹配项的索引值。如果未找到则返回 0。";
Blockly.Msg.LISTS_INLIST = "在数组中";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1是空的";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "获取长度";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回数组的长度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "建立数组使用项 %1 重复 %2 次";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重复次数的值的数组。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "为";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入在";
Blockly.Msg.LISTS_SET_INDEX_SET = "设置";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在数组的起始处添加该项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在数组中的指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在数组中指定位置的项。#1是第一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "将该项追加到数组的末尾。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在数组中随机插入项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "设置数组中的第一个项目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "设置在数组中指定位置的项。#1是最后一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "设置在数组中指定位置的项。#1是第一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "设置数组中的最后一项。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "设置数组中一个随机的项目。";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "从文本制作数组";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "从数组拆出文本";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "拆分文本到文本数组，按每个分隔符拆分。";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "用分隔符";
Blockly.Msg.LISTS_TOOLTIP = "如果改数组为空，则返回真。";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "假";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回真或假。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果两个输入结果相等，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一个输入结果比第二个大，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一个输入结果大于或等于第二个输入结果，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一个输入结果比第二个小，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一个输入结果小于或等于第二个输入结果，则返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果两个输入结果不相等，则返回真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://zh.wikipedia.org/wiki/逻辑非";
Blockly.Msg.LOGIC_NEGATE_TITLE = "非";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果输入结果为假，则返回真；如果输入结果为真，则返回假。";
Blockly.Msg.LOGIC_NULL = "空";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回空值。";
Blockly.Msg.LOGIC_OPERATION_AND = "且";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果两个输入结果都为真，则返回真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少有一个输入结果为真，则返回真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "测试";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://zh.wikipedia.org/wiki/条件运算符";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果为假";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果为真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "检查“test”中的条件。如果条件为真，则返回“if true”的值，否则，则返回“if false”的值。";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://zh.wikipedia.org/wiki/算术";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回两个数字的和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回两个数字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回两个数字的差。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回两个数字的乘积。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第一个数的第二个数次幂。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_QUYU = "返回第一个数对第二个数取余的值。";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://zh.wikipedia.org/wiki/%E5%8A%A0%E6%B3%95";
Blockly.Msg.MATH_CHANGE_INPUT_BY = "由";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "更改";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "将一个数添加到变量“%1”。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/数学常数";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一个常见常量：π (3.141......)，e (2.718...)、φ (1.618...)、 sqrt(2) (1.414......)、sqrt(½) (0.707......)或 ∞（无穷大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制数字 %1 介于 (低) %2 到 (高) %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制数字介于两个指定的数字之间";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶数";
Blockly.Msg.MATH_IS_NEGATIVE = "为负";
Blockly.Msg.MATH_IS_ODD = "是奇数";
Blockly.Msg.MATH_IS_POSITIVE = "是正值";
Blockly.Msg.MATH_IS_PRIME = "是质数";
Blockly.Msg.MATH_IS_TOOLTIP = "如果数字是偶数、奇数、非负整数、正数、负数或如果它可被某数字整除，则返回真或假。";
Blockly.Msg.MATH_IS_WHOLE = "为整数";
Blockly.Msg.MATH_MODULO_HELPURL = "https://zh.wikipedia.org/wiki/%E6%A8%A1%E9%99%A4";
Blockly.Msg.MATH_MODULO_TITLE = "取余数自 %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "返回这两个数字相除后的余数。";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://zh.wikipedia.org/wiki/数字";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一个数字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "数组中的平均数";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "数组中的最大值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "数组中位数";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "数组中的最小值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "数组模式";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "数组的随机项";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "数组中的标准差";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "数组中的数的总和";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回数组中的数值的平均值。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回数组中最大数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回数组中的中位数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回数组中最小数。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回数组中的最常见的项的数组。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "从数组中返回一个随机的元素。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回数组的标准偏差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回数组中的所有数字的和。";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://zh.wikipedia.org/wiki/随机数发生器";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "随机分数";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介于（包含）0.0到1.0之间的随机数。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://zh.wikipedia.org/wiki/随机数发生器";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "从 %1 到 %2 之间的随机整数";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "返回两个指定的范围（含）之间的随机整数。";
Blockly.Msg.MATH_ROUND_HELPURL = "https://zh.wikipedia.org/wiki/四舍五入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "向下舍入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "向下舍入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "向上舍入";
Blockly.Msg.MATH_ROUND_TOOLTIP = "数字向上或向下舍入。";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "绝对";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "平方根";
Blockly.Msg.MATH_ABS='取绝对值';
Blockly.Msg.MATH_SQ='平方';
Blockly.Msg.MATH_SQRT='平方根';
Blockly.Msg.MATH_LOG='自然对数';
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回一个数的绝对值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回数的e次幂。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回一个数的自然对数。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回数字的对数。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回数的逻辑非。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回数的10次幂。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回一个数的平方根。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_SQ = "返回一个数的平方。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_TOINT = "返回一个数的整数部分。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_QUYU_SYMBOL="%";
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函数";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回一个数的反余弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回一个数的反正弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回一个数的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的余弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
Blockly.Msg.ME = "我";
Blockly.Msg.NEW_VARIABLE = "新变量...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新变量的名称：";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "空白";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "允许声明";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "参数：";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "执行";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "运行用户定义的函数“%1”。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "运行用户定义的函数“%1”，并使用它的输出值。";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "参数：";
Blockly.Msg.PROCEDURES_CREATE_DO = "创建“%1”";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "执行";
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "procedure";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "创建一个不带输出值的函数。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "返回";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "创建一个有输出值的函数。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函数具有重复参数。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "突出显示函数定义";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值为真，则返回第二个值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 仅在定义函数内可使用此块。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "参数：";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "添加函数输入。";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "输入";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "添加、删除或重新排此函数的输入。";
Blockly.Msg.REMOVE_COMMENT = "删除注释";
Blockly.Msg.RENAME_VARIABLE = "重命名变量...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "将所有“%1”变量重命名为:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "追加文本";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "将一些文本追加到变量“%1”。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "为小写";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "为首字母大写";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "为大写";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小写复制这段文字。";
Blockly.Msg.TEXT_CHARAT_FIRST = "获得第一个字符";
Blockly.Msg.TEXT_CHARAT_FROM_END = "获得倒数第#个字符";
Blockly.Msg.TEXT_CHARAT_FROM_START = "获得字符#";
Blockly.Msg.TEXT_CHARAT = "获得第";
Blockly.Msg.TEXT_CHARAT2 = "个字符";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "于文本中";
Blockly.Msg.TEXT_CHARAT_LAST = "获得最后一个字符";
Blockly.Msg.TEXT_CHARAT_RANDOM = "获取随机的字母";
Blockly.Msg.TEXT_CHARAT_TAIL = "空白";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位于指定位置的字母。";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "将一个项添加到文本中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、删除或重新排列各节来重新配置这个文本块。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到倒数第#个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到字符#";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到最后一个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自文本";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串自第一个字符";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自#到末尾";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自#";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "空白";
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分文本。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "自文本";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "寻找第一个出现的文本";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "寻找最后一个出现的文本";
Blockly.Msg.TEXT_INDEXOF_TAIL = "空白";
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二个字串中的第一/最后一个匹配项的索引值。如果未找到则返回 0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1是空的";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的文本为空，则返回真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "建立字符串使用";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "通过串起任意数量的项以建立一段文字。";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "%1的长度";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回文本的字符数（包括空格）。";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "打印%1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "打印指定的文字、数字或其他值。";
Blockly.Msg.TEXT_PRINT_HEX_TOOLTIP = "以十六进制的格式打印指定的数字。";
Blockly.Msg.TEXT_WRITE_TOOLTIP = "以原始方式输出，可以输出16进制。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "提示用户输入数字。";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "提示用户输入一些文本。";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "输入数字并显示提示消息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "输入数字并显示提示消息";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://zh.wikipedia.org/wiki/字符串";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "一个字母、单词或一行文本。";
Blockly.Msg.TEXT_CHAR_TOOLTIP = "一个字符。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除两侧空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左侧空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右侧空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "复制这段文字的同时删除两端多余的空格。";
Blockly.Msg.TODAY = "Today";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "item";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "创建“设定%1”";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";
Blockly.Msg.VARIABLES_GET_TITLE = "";
Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此变量的值。";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "创建“获得%1”";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "到";
Blockly.Msg.VARIABLES_SET_TITLE = "赋值";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "设置此变量，以使它和输入值相等。";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
//luokailiang
Blockly.MIXLY_PINMODE = '管脚模式';
Blockly.MIXLY_PINMODEIN = 'ᠤᠷᠤᠭᠤᠯᠬᠤ';
Blockly.MIXLY_PINMODEOUT = 'ᠭᠠᠷᠭᠠᠬᠤ';
Blockly.MIXLY_PINMODEPULLUP = '上拉输入';
Blockly.MIXLY_DECLARE='声明';
Blockly.MIXLY_AS='为';
Blockly.MIXLY_VALUE='并赋值';
Blockly.MIXLY_VALUE2='赋值为';
Blockly.MIXLY_MAP='映射';
Blockly.MIXLY_MAP_FROM="从 [";
Blockly.MIXLY_MAP_TO="] 到 [";
Blockly.MIXLY_MILLIS='毫秒';
Blockly.MIXLY_DELAY='延时';
Blockly.MIXLY_ATTACHINTERRUPT_PIN='中断 管脚#';
Blockly.MIXLY_DETACHINTERRUPT_PIN = '取消中断 管脚#';
Blockly.MIXLY_ATTACHPININTERRUPT_PIN = '管脚中断 管脚#';
Blockly.MIXLY_DETACHPININTERRUPT_PIN = '取消管脚中断 管脚#';
Blockly.MIXLY_MODE='模式';
Blockly.MIXLY_DO='执行';
Blockly.MIXLY_BUILDIN_LED='内嵌LED灯';
Blockly.MIXLY_STAT='设为';
Blockly.MIXLY_DIGITALWRITE_PIN='数字输出 管脚#';
Blockly.MIXLY_DIGITALREAD_PIN='数字输入 管脚#';
Blockly.MIXLY_ANALOGWRITE_PIN='模拟输出 管脚#';
Blockly.MIXLY_ANALOGREAD_PIN='模拟输入 管脚#';
Blockly.MIXLY_SERIAL_WRITE = '原始输出';
Blockly.MIXLY_SERIAL_PRINT = 'ᠳᠠᠷᠤᠮᠠᠯᠠᠬᠤ';
Blockly.MIXLY_SERIAL_PRINTLN='打印（自动换行）';
Blockly.MIXLY_SERIAL_PRINT_HEX='打印（16进制/自动换行）';
Blockly.MIXLY_SERIAL_FLUSH='清空缓存区数据';
Blockly.MIXLY_STEP='步长为';
Blockly.MIXLY_TONE_PIN='播放声音 管脚#';
Blockly.MIXLY_FREQUENCY='频率';
Blockly.MIXLY_DURATION='持续时间';
Blockly.MIXLY_NOTONE_PIN='结束声音 管脚#';
Blockly.MIXLY_BLOCKGROUP_CATEGORY='模块组';
Blockly.MIXLY_IR_RECEIVE='红外接收 管脚#';
Blockly.MIXLY_IR_RECEIVE_ENABLE='红外接收使能 管脚#';
Blockly.MIXLY_IR_SEND_NEC1='红外发射（';
Blockly.MIXLY_IR_SEND_NEC2='） 管脚#';
Blockly.MIXLY_IR_RECEIVE_RAW='红外接收并打印数据（RAW） 管脚#';
Blockly.MIXLY_IR_SEND_RAW='红外发射（RAW） 管脚#';
Blockly.LANG_MATH_TO_INT='取整';
Blockly.MIXLY_SERVO='舵机';
Blockly.MIXLY_PIN='管脚#';
Blockly.MIXLY_DEGREE_0_180='角度 (0~180)';
Blockly.MIXLY_READ_DEGREES='读取度数';
Blockly.MIXLY_HIGH='ᠦᠨᠳᠦᠷ';
Blockly.MIXLY_LOW='低';
Blockly.MIXLY_ON='开';
Blockly.MIXLY_OFF='关';
Blockly.MIXLY_RISING='上升';
Blockly.MIXLY_FALLING='下降';
Blockly.MIXLY_CHANGE='改变';
Blockly.MIXLY_I2C_MASTER_WRITE="I2C写入 设备地址";
Blockly.MIXLY_I2C_MASTER_READ="I2C读取 设备地址";
Blockly.MIXLY_I2C_MASTER_READ2="I2C读取";
Blockly.MIXLY_I2C_VALUE="值";
Blockly.MIXLY_I2C_BYTES="字节数";
Blockly.MIXLY_I2C_AVAILABLE='读取I2C成功吗？';
Blockly.LANG_CONTROLS_FOR_INPUT_WITH = '使用';
Blockly.LANG_CONTROLS_FOR_INPUT_VAR = 'x';
Blockly.LANG_CONTROLS_FOR_INPUT_FROM = '从';
Blockly.LANG_CONTROLS_FOR_INPUT_TO = '到';
Blockly.LANG_CONTROLS_FOR_INPUT_DO = '执行';
Blockly.LANG_CONTROLS_WHILEUNTIL_TITLE_REPEAT = '重复';
Blockly.LANG_CONTROLS_WHILEUNTIL_INPUT_DO = '执行';
Blockly.LANG_CONTROLS_WHILEUNTIL_OPERATOR_WHILE = '满足条件';
Blockly.LANG_CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = '不满足条件';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_INPUT_OFLOOP = '循环';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = '跳出';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = '跳到下一个';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_WARNING = '警告：\n' +
    '这个模块只能\n' +
    '用在循环中。';
Blockly.LANG_MATH_INT = '整数';
Blockly.LANG_MATH_LONG = '长整数';
Blockly.LANG_MATH_FLOAT = '小数';
Blockly.LANG_MATH_BOOLEAN = '布尔';
Blockly.LANG_MATH_BYTE = '字节';
Blockly.LANG_MATH_CHAR = '字符';
Blockly.LANG_MATH_STRING = '字符串';
Blockly.LANG_LISTS_GET_INDEX1 = '的第';
Blockly.LANG_LISTS_GET_INDEX2 = '项';
Blockly.LANG_LISTS_GET_INDEX_TOOLTIP = '返回数组中指定位置的值。';
Blockly.LANG_LISTS_SET_INDEX1 = '的第';
Blockly.LANG_LISTS_SET_INDEX2 = '项赋值为';
Blockly.LANG_LISTS_SET_INDEX_TOOLTIP = '设置数组中指定位置的值。';
Blockly.LANG_MATH_CONSTRAIN_INPUT_CONSTRAIN = '约束';
Blockly.LANG_MATH_CONSTRAIN_INPUT_LOW = '介于 (最小值)';
Blockly.LANG_MATH_CONSTRAIN_INPUT_HIGH = '和 (最大值)';
Blockly.LANG_MATH_RANDOM_SEED = '初始化随机数';
Blockly.LANG_MATH_RANDOM_INT_INPUT_FROM = '随机数 从';
Blockly.LANG_MATH_RANDOM_INT_INPUT_TO = '到';
Blockly.MIXLY_DF_LED='LED灯';
Blockly.MIXLY_DF_BUZZER='蜂鸣器';
Blockly.MIXLY_DF_BTN='按钮（数字）';
Blockly.MIXLY_DF_VIBRATION='震动（数字）';
Blockly.MIXLY_DF_TILT='倾斜（数字）';
Blockly.MIXLY_DF_TOUCH='触摸（数字）';
Blockly.MIXLY_DF_MAGNETIC='磁感应（数字）';
Blockly.MIXLY_DF_PYROELECTRIC_INFRARED='热释电红外（数字）';
Blockly.MIXLY_MB_PYROELECTRIC_INFRARED='人体红外';
Blockly.MIXLY_DF_JOYSTICK_D='摇杆-按钮（数字）';
Blockly.MIXLY_DF_JOYSTICK_A='摇杆（模拟）';
Blockly.MIXLY_JOYSTICK='摇杆';
Blockly.MIXLY_DF_POTENTIOMETER='电位器（模拟）';
Blockly.MIXLY_POTENTIOMETER='电位器';
Blockly.MIXLY_DF_ROTATION='角度（模拟）';
Blockly.MIXLY_DF_VOLTAGE='电压（模拟）';
Blockly.MIXLY_DF_PIEZO_DISK_VIRBRATION='压电陶瓷震动（模拟）';
Blockly.MIXLY_DF_SOUND='声音（模拟）';
Blockly.MIXLY_SOUND='声音';
Blockly.MIXLY_DF_RELAY='继电器';
Blockly.MIXLY_DF_LIGHT='光线（模拟）';
Blockly.MIXLY_DF_GRAYSCALE='灰度（模拟）';
Blockly.MIXLY_DF_FLAME='火焰（模拟）';
Blockly.MIXLY_DF_TEMPERATURE='温度（模拟）';
Blockly.MIXLY_TEMPERATURE='温度（℃）';
Blockly.MIXLY_DF_ACCELEROMETER='三轴加速度（模拟）';
Blockly.MIXLY_DF_MOISTURE='土壤湿度（模拟）';
Blockly.MIXLY_DF_WATER='水分（模拟）';
Blockly.MIXLY_DF_CO='一氧化碳（模拟）';
Blockly.MIXLY_DF_SHARP_GP2Y0A21='夏普GP2Y0A21红外测距（模拟）';
Blockly.MIXLY_MAKELISTFROM='从字符串';
Blockly.MIXLY_SPLITBYDOU='创建数组';
Blockly.MIXLY_SETUP='初始化';
Blockly.MIXLY_WARNING_INTERRUPT='该管脚号不能作为中断';
Blockly.MIXLY_CHAOSHENGBO='超声波测距(cm) ';
Blockly.MIXLY_MB_CHAOSHENGBO='超声波测距';
Blockly.MIXLY_IR_RECEIVE_YES='有信号';
Blockly.MIXLY_IR_RECEIVE_NO='无信号';
Blockly.LANG_VARIABLES_SET_TITLE='赋值为';
Blockly.MIXLY_TEXT_JOIN='连接';
Blockly.MIXLY_SERIAL_AVAILABLE = '有数据可读吗？';
Blockly.MIXLY_SERIAL_EVENT = '串口中断';
Blockly.MIXLY_SERIAL_READSTR='读取字符串';
Blockly.MIXLY_SERIAL_READSTR_UNTIL='读取字符串直到';
Blockly.MIXLY_SERIAL_READ='读取';
Blockly.MIXLY_IR_RECIEVE_TOOLTIP='在接收到红外信号时进行用户自定义的处理。';
Blockly.MIXLY_IR_SEND_NEC_TOOLTIP='发射指定类型的红外数据';
Blockly.MIXLY_IR_RECIEVE_RAW_TOOLTIP='在接收到红外信号时以RAW格式打印出红外数据。';
Blockly.MIXLY_IR_SEND_RAW_TOOLTIP='发射RAW红外数据，4个参数分别是管脚号、数组、数组长度、红外信号频率';
Blockly.MIXLY_LIST_NAME='数组';
Blockly.MIXLY_LIST_LENGTH='数组长度';
Blockly.MIXLY_TO_INT='转整数';
Blockly.MIXLY_TO_FLOAT='转小数';
Blockly.MIXLY_DATA="数值";
Blockly.MIXLY_BITS="比特数";
Blockly.MIXLY_MB_LIGHT_GRAYSCALE='光线与灰度传感器';
Blockly.MIXLY_MB_LIGHT_GRAYSCALE_LED=' LED设为';
Blockly.MIXLY_MB_LIGHT_MOTOR='设置电机';
Blockly.MIXLY_MB_LIGHT_MOTOR_SPEED=' 转速为(-255~255)';
Blockly.MIXLY_DELAY_MS='毫秒';
Blockly.MIXLY_DELAY_US='微秒';
Blockly.MIXLY_DHT11='DHT11 管脚#';
Blockly.MIXLY_DHT11_T='获取温度';
Blockly.MIXLY_DHT11_H='获取湿度';
Blockly.MIXLY_LCD_RGB_BACKLIGHT='液晶RGB背光屏';
Blockly.MIXLY_DF_LCD='液晶显示屏';
Blockly.MIXLY_LCD_PRINT1='打印第1行';
Blockly.MIXLY_LCD_PRINT2='打印第2行';
Blockly.MIXLY_LCD_PRINT3='打印第3行';
Blockly.MIXLY_LCD_PRINT4='打印第4行';
Blockly.MIXLY_LCD_ROW='在第';
Blockly.MIXLY_LCD_COLUMN='行第';
Blockly.MIXLY_LCD_PRINT='列打印';
Blockly.MIXLY_LCD_SETCOLOR='设置颜色';
Blockly.MIXLY_LCD_STAT_ON='开';
Blockly.MIXLY_LCD_STAT_OFF='关';
Blockly.MIXLY_LCD_STAT_CURSOR='有光标';
Blockly.MIXLY_LCD_STAT_NOCURSOR='无光标';
Blockly.MIXLY_LCD_STAT_BLINK='闪烁';
Blockly.MIXLY_LCD_STAT_NOBLINK='不闪烁';
Blockly.MIXLY_LCD_STAT_CLEAR='清屏';
Blockly.MIXLY_7S_DISPLAY='7段数码管';
Blockly.MIXLY_NUMBER='数字';
Blockly.MIXLY_BLUETOOTH='蓝牙';
Blockly.MIXLY_BLUETOOTH_READ_STR='读取数据（返回字符串）';
Blockly.MIXLY_AVAILABLE='有数据可读？';
Blockly.MIXLY_DATAPIN='数据管脚#';
Blockly.MIXLY_CLOCKPIN='时钟管脚#';
Blockly.MIXLY_BITORDER='顺序';
Blockly.MIXLY_MSBFIRST='高位先入';
Blockly.MIXLY_LSBFIRST='低位先入';
Blockly.MIXLY_TOSTRING='转字符串';
Blockly.MIXLY_ROMEO_MOTOR='Romeo 电机';
Blockly.MIXLY_ROMEO_MOTOR_SPEED='转速';
Blockly.MIXLY_STOP='停止';
Blockly.MIXLY_PULSEIN='脉冲长度（微秒） 管脚#';
Blockly.MIXLY_PULSEIN_STAT='状态';
Blockly.MIXLY_PULSEIN_TIMEOUT='超时（微秒）';
Blockly.MIXLY_SERIAL_READ_INT='整数';
Blockly.MIXLY_SERIAL_READ_FLOAT='小数';
Blockly.MIXLY_MAX='取最大值';
Blockly.MIXLY_MIN='取最小值';
Blockly.MIXLY_WRITE_SD_FILE='写入SD 文件';
Blockly.MIXLY_SD_DATA='数据';
Blockly.MIXLY_SD_NEWLINE='换行';
Blockly.MIXLY_EEPROM_WRITE_LONG='写入(长整数) EEPROM 地址';
Blockly.MIXLY_EEPROM_READ_LONG='读取(长整数) EEPROM 地址';
Blockly.MIXLY_EEPROM_WRITE_BYTE='写入(字节) EEPROM 地址';
Blockly.MIXLY_EEPROM_READ_BYTE='读取(字节) EEPROM 地址';
Blockly.MIXLY_SENSE_MOTOR='设置马达转速为(-255~255)';
Blockly.MIXLY_SENSE_MOTOR_STOP='停止马达';
Blockly.MIXLY_SENSE_SERVO='设置舵机角度';
Blockly.MIXLY_SENSE_RGBLED='设置RGB灯的颜色为';
Blockly.MIXLY_TRAFFIC_LED='设置交通灯';
Blockly.MIXLY_EAST='东';
Blockly.MIXLY_SOUTH='南';
Blockly.MIXLY_WEST='西';
Blockly.MIXLY_NORTH='北';
Blockly.MIXLY_SENSE_BUZZER='设置蜂鸣器为';
Blockly.MIXLY_SENSE_ULTRASONIC='超声波传感器的值';
Blockly.MIXLY_SENSE_PYROELECTRIC_INFRARED='人体红外传感器被触发？';
Blockly.MIXLY_BUTTON='按钮';
Blockly.MIXLY_UP='上';
Blockly.MIXLY_DOWN='下';
Blockly.MIXLY_LEFT='左';
Blockly.MIXLY_RIGHT='右';
Blockly.MIXLY_MID='中';
Blockly.MIXLY_IS_PRESSED='被按下？';
Blockly.MIXLY_SENSE_SLIDING='滑杆传感器的值';
Blockly.MIXLY_SENSE_TEMPERATURE='温度传感器的值';
Blockly.MIXLY_SENSE_HUMIDITY='湿度传感器的值';
Blockly.MIXLY_SENSE_SOUND='声音传感器的值';
Blockly.MIXLY_SENSE_LIGHT='光线传感器的值';
Blockly.MIXLY_SENSE_WEIGHT='称重传感器的值';
Blockly.MIXLY_SENSE_IR='接收到红外信号值：';
Blockly.MIXLY_SENSE_DIGITAL_DISPLAY='设置LED数码管的值(0~99)';
Blockly.MIXLY_SENSE_DIGITAL_DISPLAY_CLOSE='关闭LED数码管';
Blockly.MIXLY_SENSE_LED_MATRIX='设置LED点阵的值(0~9)';
Blockly.MIXLY_SENSE_LED_MATRIX_CLOSE='关闭LED点阵';
Blockly.LANG_INOUT_DIGITAL_WRITE_TOOLTIP='设置指定管脚电平值';
Blockly.MIXLY_FORWARD='前进';
Blockly.MIXLY_BACKWARD='后退';
Blockly.MIXLY_TURNLEFT='左转';
Blockly.MIXLY_TURNRIGHT='右转';
Blockly.MIXLY_MBOT_SPEED='速度为(-255~255)';
Blockly.MIXLY_RUNTIME='系统运行时间';
Blockly.MIXLY_LED_ON_BOARD='板载';
Blockly.MIXLY_ALL='全部';
Blockly.MIXLY_SET_LED='设置LED';
Blockly.MIXLY_MBOT_TONE='播放声音';
Blockly.MIXLY_MBOT_NOTONE='结束声音';
Blockly.MIXLY_SHOW_FACE='表情面板';
Blockly.MIXLY_SHOW_FACE_TEXT='显示文字:';
Blockly.MIXLY_SHOW_FACE_TIME='显示时间';
Blockly.MIXLY_MBOT_SET_DISPLAY='设置数码管';
Blockly.MIXLY_MBOT_SET_LIGHT='设置光线传感器';
Blockly.MIXLY_MBOT_SET_LIGHT_LED='LED状态为';
Blockly.MIXLY_MBOT_SET_CAMERA='设置相机快门';
Blockly.MIXLY_MBOT_SET_CAMERA_STAT='状态为';
Blockly.MIXLY_MBOT_SET_CAMERA_PRESS='按下快门';
Blockly.MIXLY_MBOT_SET_CAMERA_RELEASE='松开快门';
Blockly.MIXLY_MBOT_SET_CAMERA_FOCUS_ON='开始对焦';
Blockly.MIXLY_MBOT_SET_CAMERA_FOCUS_OFF='停止对焦';
Blockly.MIXLY_MBOT_LIGHT_SENSOR='光线传感器';
Blockly.MIXLY_LIGHT_SENSOR_ON_BOARD='板载';
Blockly.MIXLY_MBOT_BUTTON='按钮';
Blockly.MIXLY_MBOT_BUTTON_PRESSED='已按下';
Blockly.MIXLY_MBOT_BUTTON_RELEASED='已松开';
Blockly.MIXLY_MBOT_LINE_FOLLOWER='巡线传感器';
Blockly.MIXLY_MBOT_JOYSTICK='摇杆';
Blockly.MIXLY_MBOT_JOYSTICK_X='X轴';
Blockly.MIXLY_MBOT_JOYSTICK_Y='Y轴';
Blockly.MIXLY_MBOT_POTENTIOMETER='电位器';
Blockly.MIXLY_MBOT_SOUND_SENSOR='音量传感器';
Blockly.MIXLY_MBOT_LIMIT_SWITCH='限位开关';
Blockly.MIXLY_MBOT_TEMPERATURE='当前温度';
Blockly.MIXLY_MBOT_PIR_MOTION_SENSOR='人体红外传感器';
Blockly.MIXLY_MBOT_IR_REMOTE='红外遥控器按下';
Blockly.MIXLY_MBOT_IR_REMOTE_PRESSED='键';
Blockly.MIXLY_SETTING='设置';
Blockly.MIXLY_SEND_MBOT_MESSAGE='发送mBot消息';
Blockly.MIXLY_MBOT_MESSAGE_RECEIVED='接收到的mBot消息';
Blockly.MIXLY_LABPLUS_ROBOT_MOVEMENT='设置机器人移动模式为';
Blockly.MIXLY_LABPLUS_ROBOT_MOVEMENT_GO_FORWARD='前进';
Blockly.MIXLY_LABPLUS_ROBOT_MOVEMENT_STOP='停止';
Blockly.MIXLY_LABPLUS_ROBOT_MOVEMENT_GO_BACK='后退';
Blockly.MIXLY_LABPLUS_ROBOT='设置机器人';
Blockly.MIXLY_LABPLUS_ROBOT_TURN_LEFT='左转';
Blockly.MIXLY_LABPLUS_ROBOT_TURN_RIGHT='右转';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY='设置屏幕显示为';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_SMILE='微笑';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_NOSMILE='悲伤';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_CLOSE_EYE='闭眼';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_LEFT='左箭头';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_RIGHT='右箭头';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_TIAOWEN='条纹';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_ZEBRA='斑马纹';
Blockly.MIXLY_LABPLUS_ROBOT_DISPLAY_NOTHING='黑屏';
Blockly.MIXLY_LABPLUS_ROBOT_LED_TOP='设置顶灯为';
Blockly.MIXLY_LABPLUS_ROBOT_LED_SIDE='设置侧灯颜色为';
Blockly.MIXLY_LCD_ADDRESS="设备地址";
var MSG = {
  catInOut: "输入/输出",
  catControl: "控制",
  catMath: "数学",
  catText: "文本",
  catLists: "数组",
  catLogic: "逻辑",
  catSerialPort:"串口",
  catGroup: "通信",
  catStorage:"存储",
  catSensor: "传感器",
  catActuator: "执行器",
  catMonitor:"显示器",
  catVar: "变量",
  catFun: "函数",
  catEthernet:"以太网",
  catNetwork:"网络",
  catEthernet_init:"初始化",
  catEthernet_clinet:"客户端",
  catSense: "盛思(盒子)",
  catSense2: "盛思(机器人)",
  catLuxe:"泺喜机器人",
  tab_blocks: "模块",
  tab_arduino: "代码",
  copyright:"Copyright © 北师大教育学部创客教育实验室  maker.bnu.edu.cn",
  viewNormal:"普通视图",
  viewAdvanced:"高级视图"
};
Blockly.MIXLY_TOOLTIP_INOUT_HIGHLOW='返回高电平或低电平';
Blockly.MIXLY_TOOLTIP_INOUT_DIGITAL_READ='返回指定管脚的电平值';
Blockly.MIXLY_TOOLTIP_INOUT_ANALOG_WRITE='设置指定管脚的值(0~255)';
Blockly.MIXLY_TOOLTIP_INOUT_ANALOG_READ='返回指定管脚的值(0~1023)';
Blockly.MIXLY_TOOLTIP_INOUT_ATTACHINTERRUPT='设置指定管脚的中断';
Blockly.MIXLY_TOOLTIP_INOUT_DETACHINTERRUPT='取消指定管脚的中断';
Blockly.MIXLY_TOOLTIP_CONTROL_SETUP='初始化操作(这里面的内容只执行一次)';
Blockly.MIXLY_TOOLTIP_CONTROL_DELAY='延迟指定时间';
Blockly.MIXLY_TOOLTIP_CONTROL_MILLIS='返回系统运行的时间';
Blockly.MIXLY_TOOLTIP_VARIABLES_DECLARE='声明并初始化一个变量';
Blockly.MIXLY_TOOLTIP_MATH_MAX='返回2个数中较大的那个';
Blockly.MIXLY_TOOLTIP_MATH_MIN='返回2个数中较小的那个';
Blockly.MIXLY_TOOLTIP_MATH_MAP='将一个数从第一个区间映射到第二个区间，并返回映射之后的值。';
Blockly.MIXLY_TOOLTIP_TEXT_JOIN='将2个字符串拼接成一个字符串。';
Blockly.MIXLY_TOOLTIP_TEXT_TOTEXT='将一个数字转为一个字符串。';
Blockly.MIXLY_TOOLTIP_TEXT_TOINT='将一个字符串转为一个整数。';
Blockly.MIXLY_TOOLTIP_TEXT_TOFLOAT='将一个字符串转为一个小数。';
Blockly.MIXLY_TOOLTIP_LISTS_CREATE_WITH_TEXT='通过一个字符串来创建一个数组。';
Blockly.MIXLY_TOOLTIP_LOGIT_TRUEORFALSE='如果第一个数为真，则返回第二个数，否则返回第三个数。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_SERIAL_AVAILABLE='如果串口有数据可读，返回真，否则返回假。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_SERIAL_READ_STR='返回串口中的字符串。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_SERIAL_READ_INT='返回串口中的整数。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_SERIAL_READ_FLOAT='返回串口中的小数。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_CHAOSHENGBO='返回超声波传感器测得的距离。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_DHT11_TEM='返回温湿度传感器测得的温度。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_DHT11_HUM='返回温湿度传感器测得的湿度。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_SERVO_MOVE = '在0~180°间旋转。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_SERVO_READ = '返回舵机当前停留的角度。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_TONE = '按指定的频率播放声音。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_TONE2 = '按指定的频率和持续时间播放声音。';
Blockly.MIXLY_TOOLTIP_BLOCKGROUP_NOTONE = '停止播放声音。';
Blockly.LUXE_LED='灯 #';
Blockly.LUXE_MOTOR='电机 #';
Blockly.LUXE_STAT='为';
Blockly.LUXE_SPEED='速度为';
Blockly.LUXE_DIR='方向为';
Blockly.LUXE_LED_ON='亮';
Blockly.LUXE_LED_OFF='灭';
Blockly.LUXE_MOTOR_FORWARD='顺时针';
Blockly.LUXE_MOTOR_REVERSE='逆时针';
Blockly.LUXE_LED_CHANGE='转换状态';
Blockly.LUXE_MOTOR_CHANGE='改变方向';
Blockly.LUXE_MOTOR_STOP='停止';
Blockly.LUXE_SPEAKER_PLAYSOUND='播放声音';
Blockly.LUXE_SPEANER_NOSOUND='停止播放声音';
Blockly.LUXE_SPEAKER_FREQUENCY='频率';
Blockly.LUXE_SPEAKER_DURATION='持续时间';

//-----------------NOVA---------------------------------
Blockly.MIXLY_NOVA_PORT = '端口';
Blockly.MIXLY_NOVA_STAT = '设为';
Blockly.MIXLY_NOVA_GET_STAT = '获取';

// LED
Blockly.MIXLY_NOVA_LED = 'LED灯';
Blockly.MIXLY_NOVA_LED_ON = '开';
Blockly.MIXLY_NOVA_LED_OFF = '关';

// Button
Blockly.MIXLY_NOVA_BUTTON_PRESSED = '按下';
Blockly.MIXLY_NOVA_BUTTON_RELEASED = '松开';
Blockly.MIXLY_NOVA_BTN = '按钮';
Blockly.MIXLY_NOVA_ABCD = '#';

Blockly.MIXLY_NOVA_TILTSWITCH = '倾斜开关';
Blockly.MIXLY_NOVA_SOUND = '声音传感器'; 
Blockly.MIXLY_NOVA_LIMISWICTH = '限位开关'; 
Blockly.MIXLY_NOVA_LIGHT = '光敏'; 

Blockly.MIXLY_NOVA_BUZZER = '蜂鸣器'; 
Blockly.MIXLY_NOVA_FREQUENCY = '频率(Hz)'; 
Blockly.MIXLY_NOVA_MIXLY_DURATION = '持续时间(ms)'; 

Blockly.MIXLY_NOVA_MOTOR = '直流电机'; 
Blockly.MIXLY_NOVA_MOTOR_SPEED = '转速(-100~100)%'; 

Blockly.MIXLY_NOVA_ULTRASONIC = '超声波测距(cm)'; 

Blockly.MIXLY_NOVA_DHT11 = '温湿度';
Blockly.MIXLY_NOVA_TYPE = '类型';
Blockly.MIXLY_NOVA_DHT11_H = '获取湿度';
Blockly.MIXLY_NOVA_DHT11_T = '获取温度';

Blockly.MIXLY_NOVA_SERVO = '舵机';
Blockly.MIXLY_NOVA_DEGREE_0_180 = '角度（0~180）';
Blockly.MIXLY_NOVA_DELAY = '延时';
Blockly.MIXLY_NOVA_DELAY_MS = '毫秒';

Blockly.MIXLY_NOVA_LINEFINDER = '巡线';
Blockly.MIXLY_NOVA_L = '左边状态';
Blockly.MIXLY_NOVA_R = '右边状态';
Blockly.MIXLY_NOVA_READ = '获取黑白线状态';

Blockly.MIXLY_NOVA_4DIGITDISPLAY = '数码管';
Blockly.MIXLY_NOVA_DISPLAY_NUMBER = '显示数字';
Blockly.MIXLY_NOVA_DISPLAY_HOUR= '显示小时';
Blockly.MIXLY_NOVA_DISPLAY_MIN = '显示分钟';

Blockly.MIXLY_NOVA_RTC = '时钟';
Blockly.MIXLY_NOVA_RTC_SEC = '秒';
Blockly.MIXLY_NOVA_RTC_MIN = '分';
Blockly.MIXLY_NOVA_RTC_HOUR = '时';
Blockly.MIXLY_NOVA_RTC_WEEK = '星期';
Blockly.MIXLY_NOVA_RTC_DAY = '日';
Blockly.MIXLY_NOVA_RTC_MON = '月';
Blockly.MIXLY_NOVA_RTC_YEAR = '年';

Blockly.MIXLY_NOVA_IR_REC = '红外接收';

Blockly.MIXLY_NOVA_BLUETOOTH = '蓝牙';
Blockly.MIXLY_NOVA_BLUETOOTH_AVAILABLE = '有数据可读？';
Blockly.MIXLY_NOVA_BLUETOOTH_READ_STR = '读取数据（返回字符串）';
Blockly.MIXLY_NOVA_BLUETOOTH_READ_NUM = '读取数据（返回数字）';

//spi
Blockly.TO_SPI_SLAVE_PIN='向SPI从机#';
Blockly.SPI_TRANSFER='传输';

Blockly.MIXLY_SERIAL_BEGIN='波特率';

//stepper
Blockly.MIXLY_STEPPER='步进电机';
Blockly.MIXLY_STEPPER_SETUP_STEPPER='初始化步进电机';
Blockly.MIXLY_STEPPER_PIN1='管脚1#';
Blockly.MIXLY_STEPPER_PIN2='管脚2#';
Blockly.MIXLY_STEPPER_PIN3='管脚3#';
Blockly.MIXLY_STEPPER_PIN4='管脚4#';
Blockly.MIXLY_STEPSPERREVOLUTION='每转步数';
Blockly.MIXLY_STEPPER_SET_SPEED='设置转速';
Blockly.MIXLY_STEPPER_STEP='移动步数';

//-----------------Ethernet------------------------------------
Blockly.MIXLY_ETHERNET_BEGIN='初始化 (DHCP)';
Blockly.MIXLY_ETHERNET='以太网';
Blockly.MIXLY_ETHERNET2='以太网2';
Blockly.MIXLY_ETHERNET_MAC_ADDRESS='Mac地址';
Blockly.MIXLY_ETHERNET_LOCALIP='本地IP';
Blockly.MIXLY_ETHERNET_CLINET_CONNECT_SERVER='客户端连接到服务器';
Blockly.MIXLY_ETHERNET_CLINET_PORT='端口';
Blockly.MIXLY_ETHERNET_CLINET_STOP='客户端-停止';
Blockly.MIXLY_ETHERNET_CLINET_CONNECTED='客户端-已连接';
Blockly.MIXLY_ETHERNET_CLINET_AVAILABLE='客户端-有数据可读';
Blockly.MIXLY_ETHERNET_CLINET_PRINT='客户端-打印';
Blockly.MIXLY_ETHERNET_CLINET_PRINTLN='客户端-打印（自动换行）';
Blockly.MIXLY_ETHERNET_CLINET_READ='客户端-读取';
Blockly.MIXLY_ETHERNET_CLINET_GET_REQUEST='GET请求';
Blockly.MIXLY_ETHERNET_CLINET_URL='URL';
Blockly.MIXLY_ETHERNET_CLINET_SERVER='服务器';
//lm35温度传感器
Blockly.MIXLY_LM35='LM35温度传感器';

//DS18B20温度传感器
Blockly.MIXLY_DS18B20='DS18B20 管脚#';
Blockly.MIXLY_DS18B20_GET_TEMP='获取温度';
Blockly.MIXLY_DS18B20_C='°C';
Blockly.MIXLY_DS18B20_F='°F';

//GPS
Blockly.MIXLY_GPS_INIT='GPS初始化';
Blockly.MIXLY_GPS_DATA_AVAILABLE='GPS获取到数据';
Blockly.MIXLY_GPS_DATA_ENCODE='GPS解析数据成功';
Blockly.MIXLY_GPS_LOCATION='位置';
Blockly.MIXLY_GPS_DATE='日期';
Blockly.MIXLY_GPS_TIME='时间';
Blockly.MIXLY_GPS_ISVALID='有效';
Blockly.MIXLY_GPS_GET='GPS获取';
Blockly.MIXLY_GPS_LOCATION_LAT='位置-纬度';
Blockly.MIXLY_GPS_LOCATION_LNG='位置-经度';
Blockly.MIXLY_GPS_DATE_YEAR='日期-年';
Blockly.MIXLY_GPS_DATE_MONTH='日期-月';
Blockly.MIXLY_GPS_DATE_DAY='日期-日';
Blockly.MIXLY_GPS_TIME_HOUR='时间-时';
Blockly.MIXLY_GPS_TIME_MINUTE='时间-分';
Blockly.MIXLY_GPS_TIME_SECOND='时间-秒';
Blockly.MIXLY_GPS_TIME_CENTISECOND='时间-厘秒';

//factory
Blockly.MIXLY_PARAMS = '参数';

//MsTimer2
Blockly.MIXLY_MSTIMER2_EVERY='每隔';
Blockly.MIXLY_MSTIMER2_DO='执行';
Blockly.MIXLY_MSTIMER2_START='启动';
Blockly.MIXLY_MSTIMER2_STOP='停止';
//interrupts
Blockly.MIXLY_CONTROL_INTERRUPTS = '允许中断';
Blockly.MIXLY_CONTROL_NOINTERRUPTS = '禁止中断';

//others
Blockly.MIXLY_WARNING_NOT_DECLARE='该变量未声明';
Blockly.MIXLY_LENGTH = "获取长度";
Blockly.MIXLY_EQUALS="等于";
Blockly.MIXLY_STARTSWITH="开始于";
Blockly.MIXLY_ENDSWITH="结尾于";
Blockly.MIXLY_COMPARETO="比较";
Blockly.MIXLY_COMPARETO_HELP="按字典顺序比较，相等则返回0，大于则返回大于0的值，小于则返回小于0的值";
Blockly.Msg.UNDO = "撤销";
Blockly.Msg.REDO = "重做";
Blockly.MIXLY_CONTROL_END_PROGRAM = "停止程序";

//oled
Blockly.Msg.texttodisplay = "显示文本：";
Blockly.Msg.numtodisplay = "显示数字：";
Blockly.Msg.todisplay = "显示：";
Blockly.Msg.rawx = "行坐标x:(最大127)";
Blockly.Msg.liney = "列坐标y:(最大63)";
Blockly.Msg.line1 = "第一行";
Blockly.Msg.line2 = "第二行";
Blockly.Msg.line3 = "第三行";
Blockly.Msg.line4 = "第四行";
Blockly.Msg.num1 = "数字1";
Blockly.Msg.num2 = "数字2";
Blockly.Msg.num3 = "数字3";
Blockly.Msg.num4 = "数字4";
// RGB
Blockly.MIXLY_RUILONG_RGB = 'RGB灯';
Blockly.MIXLY_RUILONG_RGB_NUM = '灯号(1~4)';
Blockly.MIXLY_RUILONG_RGB_R = 'R值';
Blockly.MIXLY_RUILONG_RGB_G = 'G值';
Blockly.MIXLY_RUILONG_RGB_B = 'B值';

//四位数码管
Blockly.MIXLY_RUILONG_4DIGITDISPLAY = '四位数码管';
Blockly.MIXLY_RUILONG_4DIGITDISPLAY_DISPLAYSTRING = '显示字符串';
Blockly.MIXLY_RUILONG_4DIGITDISPLAY_NOMBER1 = '第';
Blockly.MIXLY_RUILONG_4DIGITDISPLAY_NOMBER2 = '个';
Blockly.MIXLY_RUILONG_4DIGITDISPLAY_DOT = '小数点';
Blockly.MIXLY_RUILONG_4DIGITDISPLAY_ON = '亮';
Blockly.MIXLY_RUILONG_4DIGITDISPLAY_OFF = '灭';