// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh.hant');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "添加注釋";
Blockly.Msg.AUTH = "請授權這個應用程序以保存您的作品並共亯。";
Blockly.Msg.CHANGE_VALUE_TITLE = "更改值：";
Blockly.Msg.CHAT = "通過在此框輸入與您的合作者溝通！";
Blockly.Msg.CLEAN_UP = "清理塊"; 
Blockly.Msg.COLLAPSE_ALL = "折疊塊";
Blockly.Msg.COLLAPSE_BLOCK = "折疊塊";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "顏色1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "顏色2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "用一个個給的比率(0.0-1.0)混合兩種顏色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/颜色";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "從調色板中選擇一種顏色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "隨機顏色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "隨機選擇一種顏色。";
Blockly.Msg.COLOUR_RGB_BLUE = "藍色";
Blockly.Msg.COLOUR_RGB_GREEN = "綠色";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "紅色";
Blockly.Msg.COLOUR_RGB_TITLE = "顏色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "通過指定紅色、綠色和藍色的量創建一種顏色。所有的值必須介於0和100之間。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "中斷迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "繼續下一次迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "中斷包含它的迴圈。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳過這個迴圈的剩餘部分,並繼續下一次反覆運算。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告：此塊僅可用於在一個迴圈內。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each用于每个块";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "在數組中";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "為每個項目";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍歷每個數組中的項目,將變數“%1”設定到該項中,然後執行某些語句。";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO = "from %1 to %2";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "從範圍%1到%2每隔%3";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "使用";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "從起始數到結尾數中取出變數“%1”的值,按指定的間隔,執行指定的塊。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "在if語句塊中新增一個條件。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "添加一個最終的,包括所有情况的節到if塊中。";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "新增、删除或重新排列各節來重新配寘“f”塊。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否則";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否則如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "如果值為真,執行一些語句。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "如果值為真,則執行語句的第一塊;否則,則執行語句的第二塊。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一個值為真,則執行語句的第一個塊;否則,如果第二個值為真,則執行語句的第二塊。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一個值為真,則執行語句的第一塊;否則,如果第二個值為真,則執行語句的第二塊;如果沒有值為真,則執行語句的最後一塊。";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For回圈";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "執行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重複%1次";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "重複";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "次";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次執行一些語句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重複直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重複當";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "只要值為假,執行一些語句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "只要值為真,執行一些語句。";
Blockly.Msg.DELETE_BLOCK = "删除塊";
Blockly.Msg.DELETE_X_BLOCKS = "删除%1塊";
Blockly.Msg.DISABLE_BLOCK = "禁用塊";
Blockly.Msg.DUPLICATE_BLOCK = "複製";
Blockly.Msg.ENABLE_BLOCK = "啟用塊";
Blockly.Msg.EXPAND_ALL = "展開塊";
Blockly.Msg.EXPAND_BLOCK = "展開塊";
Blockly.Msg.EXTERNAL_INPUTS = "外部輸入";
Blockly.Msg.HELP = "幫助";
Blockly.Msg.INLINE_INPUTS = "單行輸入";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://en.wikipedia.org/wiki/Linked_list#Empty_lists";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "初始化為空數組";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一個數組,長度為0,不包含任何數據記錄";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "數組";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "新增、删除或重新排列各部分以此重新配寘這個數組塊。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "初始化數組為";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "將一個項添加到數組中。。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一個具有任意數量項目的數組。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒數第#";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "獲得";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出並移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最後";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "隨機";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "空白";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回數組中的第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在數組中的指定位置的項。# 1是最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在數組中的指定位置的項。# 1是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回數組中的最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "隨機返回數組中的一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST ="移除並返回數組中的第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END ="移除並返回數組中的指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START ="移除並返回數組中的指定位置的項。#1是第一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST ="移除並返回數組中的最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM ="移除並返回數組中的一個隨機項目中。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST ="移除數組中的第一項";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END ="删除在數組中的指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START ="移除在數組中的指定位置的項。#1是第一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST ="移除數組中的最後一項";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM ="删除數組中的一個隨機的項。";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END ="到倒數第#";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START ="到#";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST ="到最後";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL ="https://github.com/google/blockly/wiki/Lists#getting-a-sublist";// untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST ="從頭獲得子數組";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END ="從倒數#取得子數組";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START ="從#取得子數組";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL ="空白";
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP ="複製數組中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST ="找出第一個項出現";
Blockly.Msg.LISTS_INDEX_OF_HELPURL ="https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";// untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST ="找出最後一個項出現";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP ="返回在數組中的第一/最後一個匹配項的索引值。如果未找到則返回0。";
Blockly.Msg.LISTS_INLIST ="在數組中";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL ="https://github.com/google/blockly/wiki/Lists#is-empty";// untranslated
Blockly.Msg.LISTS_IS_EMPTY_TITLE ="%1是空的";
Blockly.Msg.LISTS_LENGTH_HELPURL ="https://github.com/google/blockly/wiki/Lists#length-of";// untranslated
Blockly.Msg.LISTS_LENGTH_TITLE ="獲取長度";
Blockly.Msg.LISTS_LENGTH_TOOLTIP ="返回數組的長度。";
Blockly.Msg.LISTS_REPEAT_HELPURL ="https://github.com/google/blockly/wiki/Lists#create-list-with";// untranslated
Blockly.Msg.LISTS_REPEAT_TITLE ="建立數組使用項%1重複%2次";
Blockly.Msg.LISTS_REPEAT_TOOLTIP ="建立包含指定重複次數的值的數組。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL ="https://github.com/google/blockly/wiki/Lists#in-list--set";// untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO ="為";
Blockly.Msg.LISTS_SET_INDEX_INSERT ="插入在";
Blockly.Msg.LISTS_SET_INDEX_SET ="設定";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST ="在數組的起始處添加該項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END ="插入在數組中的指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START ="插入在數組中指定位置的項。#1是第一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST ="將該項追加到數組的末尾。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM ="在數組中隨機插入項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST ="設定數組中的第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END ="設定在數組中指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START ="設定在數組中指定位置的項。#1是第一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST ="設定數組中的最後一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM ="設定數組中一個隨機的項目。";
Blockly.Msg.LISTS_SPLIT_HELPURL ="https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT ="從文字製作數組";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST ="從數組拆出文字";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN ="Join a list of texts into one text,separated by a delimiter.";// untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT ="折開文字到文字數組,按每個分隔符號折開。";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER ="用分隔符號";
Blockly.Msg.LISTS_TOOLTIP ="如果改數組為空,則返回真。";
Blockly.Msg.LOGIC_BOOLEAN_FALSE ="假";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP ="返回真或假。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE ="真";
Blockly.Msg.LOGIC_COMPARE_HELPURL ="https://zh.wikipedia.org/wiki/不等";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ ="如果兩個輸入結果相等,則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT ="如果第一個輸入結果比第二個大,則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE ="如果第一個輸入結果大於或等於第二個輸入結果,則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT ="如果第一個輸入結果比第二個小,則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE ="如果第一個輸入結果小於或等於第二個輸入結果,則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ ="如果兩個輸入結果不相等,則返回真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL ="https://zh.wikipedia.org/wiki/邏輯非";
Blockly.Msg.LOGIC_NEGATE_TITLE ="非";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP ="如果輸入結果為假,則返回真;如果輸入結果為真,則返回假。";
Blockly.Msg.LOGIC_NULL ="空";
Blockly.Msg.LOGIC_NULL_HELPURL ="https://en.wikipedia.org/wiki/Nullable_type";// untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP ="返回空值。";
Blockly.Msg.LOGIC_OPERATION_AND ="且";
Blockly.Msg.LOGIC_OPERATION_HELPURL ="https://github.com/google/blockly/wiki/Logic#logical-operations";// untranslated
Blockly.Msg.LOGIC_OPERATION_OR ="或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND ="如果兩個輸入結果都為真,則返回真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR ="如果至少有一個輸入結果為真,則返回真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION ="測試";
Blockly.Msg.LOGIC_TERNARY_HELPURL ="https://zh.wikipedia.org/wiki/條件運算子";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE ="如果為假";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE ="如果為真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP ="檢查“test”中的條件。如果條件為真,則返回“f true”的值,否則,則返回“if false”的值。";
Blockly.Msg.MATH_ADDITION_SYMBOL ="+";// untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL ="https://zh.wikipedia.org/wiki/算术";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD ="返回兩個數位的和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE ="返回兩個數位的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS ="返回兩個數位的差。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY ="返回兩個數位的乘積。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER ="返回第一個數的第二個數次幂。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_QUYU ="返回第一個數對第二個數取餘的值。";
Blockly.Msg.MATH_CHANGE_HELPURL ="https://zh.wikipedia.org/wiki/%E5%8A%A0%E6%B3%95";
Blockly.Msg.MATH_CHANGE_INPUT_BY ="由";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE ="更改";
Blockly.Msg.MATH_CHANGE_TOOLTIP ="將一個數添加到變數“%1”。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/数学常数";
Blockly.Msg.MATH_CONSTANT_TOOLTIP ="返回一個常見常數：π（3.141……）,e（2.718…）、φ（1.618…）、sqrt（2）（1.414……）、sqrt（½）（0.707……）或∞（無窮大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL ="https://en.wikipedia.org/wiki/Clamping_%28graphics%29";
Blockly.Msg.MATH_CONSTRAIN_TITLE ="限制數位%1介於（低）%2到（高）%3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP ="限制數位介於兩個指定的數位之間";
Blockly.Msg.MATH_DIVISION_SYMBOL ="÷";// untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY ="可被整除";
Blockly.Msg.MATH_IS_EVEN ="是偶數";
Blockly.Msg.MATH_IS_NEGATIVE ="為負";
Blockly.Msg.MATH_IS_ODD ="是奇數";
Blockly.Msg.MATH_IS_POSITIVE ="是正值";
Blockly.Msg.MATH_IS_PRIME ="是質數";
Blockly.Msg.MATH_IS_TOOLTIP ="如果數位是偶數、奇數、非負整數、正數、負數或如果它可被某數位整除,則返回真或假。";
Blockly.Msg.MATH_IS_WHOLE ="為整數";
Blockly.Msg.MATH_MODULO_HELPURL ="https://zh.wikipedia.org/wiki/%E6%A8%A1%E9%99%A4";
Blockly.Msg.MATH_MODULO_TITLE ="取餘數自%1÷%2";
Blockly.Msg.MATH_MODULO_TOOLTIP ="返回這兩個數位相除後的餘數。";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL ="×";// untranslated
Blockly.Msg.MATH_NUMBER_HELPURL ="https://zh.wikipedia.org/wiki/数字";
Blockly.Msg.MATH_NUMBER_TOOLTIP ="一個數位。";
Blockly.Msg.MATH_ONLIST_HELPURL ="";// untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE ="數組中的平均數";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX ="數組中的最大值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN ="數組中位數";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN ="數組中的最小值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE ="數組模式";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM ="數組的隨機項";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV ="數組中的標準差";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM ="數組中的數的總和";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE ="返回數組中的數值的平均值。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX ="返回數組中最大數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN ="返回數組中的中位數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN ="返回數組中最小數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE ="返回數組中的最常見的項的數組。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM ="從數組中返回一個隨機的元素。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV ="返回數組的標準差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM ="返回數組中的所有數位的和。";
Blockly.Msg.MATH_POWER_SYMBOL ="^";// untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL ="https://zh.wikipedia.org/wiki/随机数发生器";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM ="隨機分數";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP ="返回介於（包含）0.0到1.0之間的亂數。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL ="https://zh.wikipedia.org/wiki/随机数发生器";
Blockly.Msg.MATH_RANDOM_INT_TITLE ="從%1到%2之間的隨機整數";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP ="返回兩個指定的範圍（含）之間的隨機整數。";
Blockly.Msg.MATH_ROUND_HELPURL ="https://zh.wikipedia.org/wiki/四舍五入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND ="向下舍入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN ="向下舍入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP ="向上舍入";
Blockly.Msg.MATH_ROUND_TOOLTIP ="數位向上或向下舍入。";
Blockly.Msg.MATH_SINGLE_HELPURL ="https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE ="絕對";
Blockly.Msg.MATH_SINGLE_OP_ROOT ="平方根";
Blockly.Msg.MATH_ABS='取絕對值';
Blockly.Msg.MATH_SQ='平方';
Blockly.Msg.MATH_SQRT='平方根';
Blockly.Msg.MATH_LOG='自然對數';
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS ="返回一個數的絕對值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP ="返回數的e次幂。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN ="返回一個數的自然對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 ="返回數位的對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG ="返回數的邏輯非。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 ="返回數的10次幂。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT ="返回一個數的平方根。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_SQ ="返回一個數的平方。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_TOINT ="返回一個數的整數部分。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_QUYU_SYMBOL="%";
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函数";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS ="返回一個數的反余弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN ="返回一個數的反正弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN ="返回一個數的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS ="返回指定角度的余弦值（非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN ="返回指定角度的正弦值（非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN ="返回指定角度的正切值（非弧度）。";
Blockly.Msg.ME ="我";
Blockly.Msg.NEW_VARIABLE ="新變數…";
Blockly.Msg.NEW_VARIABLE_TITLE ="新變數的名稱：";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX ="空白";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS ="允許聲明";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS ="參數：";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL ="執行";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL ="https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP ="運行用戶定義的函數“%1”。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL ="https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP ="運行用戶定義的函數“%1”,並使用它的輸出值。";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS ="參數：";
Blockly.Msg.PROCEDURES_CREATE_DO ="創建“%1”";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO ="執行";
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL ="https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE ="procedure";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE ="";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP ="創建一個不帶輸出值的函數。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL ="https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN ="返回";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP ="創建一個有輸出值的函數。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING ="警告：此函數具有重複參數。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF ="突出顯示函數定義";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP ="如果值為真,則返回第二個值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING ="警告：僅在定義函數內可使用此塊。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE ="參數：";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP ="添加函數輸入。";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE ="輸入";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP ="添加、删除或重新排此函數的輸入。";
Blockly.Msg.REMOVE_COMMENT ="删除注釋";
Blockly.Msg.RENAME_VARIABLE ="重命名變數…";
Blockly.Msg.RENAME_VARIABLE_TITLE ="將所有“%1”變數重命名為：";
Blockly.Msg.TEXT_APPEND_APPENDTEXT ="追加文字";
Blockly.Msg.TEXT_APPEND_HELPURL ="https://github.com/google/blockly/wiki/Text#text-modification";// untranslated
Blockly.Msg.TEXT_APPEND_TO ="在";
Blockly.Msg.TEXT_APPEND_TOOLTIP ="將一些文字追加到變數“%1”。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL ="https://github.com/google/blockly/wiki/Text#adjusting-text-case";// untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE ="為小寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE ="為首字母大寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE ="為大寫";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP ="使用不同的大小寫複製這段文字。";
Blockly.Msg.TEXT_CHARAT_FIRST ="獲得第一個字元";
Blockly.Msg.TEXT_CHARAT_FROM_END ="獲得倒數第#個字元";
Blockly.Msg.TEXT_CHARAT_FROM_START ="獲得字元#";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT ="於文字中";
Blockly.Msg.TEXT_CHARAT_LAST ="獲得最後一個字元";
Blockly.Msg.TEXT_CHARAT_RANDOM ="獲取隨機的字母";
Blockly.Msg.TEXT_CHARAT_TAIL ="空白";
Blockly.Msg.TEXT_CHARAT_TOOLTIP ="返回位於指定位置的字母。";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP ="將一個項添加到文字中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN ="加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP ="添加、删除或重新排列各節來重新配寘這個文字塊。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END ="到倒數第#個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START ="到字元#";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST ="到最後一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL ="https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";// untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT ="自文字";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST ="取得一段字串自第一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END ="取得一段字串自#到末尾";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START ="取得一段字串自#";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL ="空白";
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP ="返回指定的部分文字。";
Blockly.Msg.TEXT_INDEXOF_HELPURL ="https://github.com/google/blockly/wiki/Text#finding-text";// untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT ="自文字";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST ="尋找第一個出現的文字";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST ="尋找最後一個出現的文字";
Blockly.Msg.TEXT_INDEXOF_TAIL ="空白";
Blockly.Msg.TEXT_INDEXOF_TOOLTIP ="返回在第二個字串中的第一/最後一個匹配項的索引值。如果未找到則返回0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL ="https://github.com/google/blockly/wiki/Text#checking-for-empty-text";// untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE ="%1是空的";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP ="如果提供的文字為空,則返回真。";
Blockly.Msg.TEXT_JOIN_HELPURL ="https://github.com/google/blockly/wiki/Text#text-creation";// untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH ="建立字串使用";
Blockly.Msg.TEXT_JOIN_TOOLTIP ="通過串起任意數量的項以建立一段文字。";
Blockly.Msg.TEXT_LENGTH_HELPURL ="https://github.com/google/blockly/wiki/Text#text-modification";// untranslated
Blockly.Msg.TEXT_LENGTH_TITLE ="%1的長度";
Blockly.Msg.TEXT_LENGTH_TOOLTIP ="返回文字的字元數（包括空格）。";
Blockly.Msg.TEXT_PRINT_HELPURL ="https://github.com/google/blockly/wiki/Text#printing-text";// untranslated
Blockly.Msg.TEXT_PRINT_TITLE ="列印%1";
Blockly.Msg.TEXT_PRINT_TOOLTIP ="列印指定的文字、數位或其他值。";
Blockly.Msg.TEXT_PRINT_HEX_TOOLTIP ="以十六進位的格式列印指定的數位。";
Blockly.Msg.TEXT_PROMPT_HELPURL ="https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";// untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER ="提示用戶輸入數位。";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT ="提示用戶輸入一些文字。";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER ="輸入數位並顯示提示消息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT ="輸入數位並顯示提示消息";
Blockly.Msg.TEXT_TEXT_HELPURL ="https://zh.wikipedia.org/wiki/字串";
Blockly.Msg.TEXT_TEXT_TOOLTIP ="一個字母、單詞或一行文字。";
Blockly.Msg.TEXT_CHAR_TOOLTIP = "一個字符。";
Blockly.Msg.TEXT_TRIM_HELPURL ="https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";// untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH ="消除兩側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT ="消除左側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT ="消除右側空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP ="複製這段文字的同時删除兩端多餘的空格。";
Blockly.Msg.TODAY = "Today";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "item";
Blockly.Msg.VARIABLES_GET_CREATE_SET ="創建“設定%1”";
Blockly.Msg.VARIABLES_GET_HELPURL ="https://github.com/google/blockly/wiki/Variables#get";// untranslated
Blockly.Msg.VARIABLES_GET_TAIL ="";
Blockly.Msg.VARIABLES_GET_TITLE ="";
Blockly.Msg.VARIABLES_GET_TOOLTIP ="返回此變數的值。";
Blockly.Msg.VARIABLES_SET_CREATE_GET ="創建“獲得%1”";
Blockly.Msg.VARIABLES_SET_HELPURL ="https://github.com/google/blockly/wiki/Variables#set";// untranslated
Blockly.Msg.VARIABLES_SET_TAIL ="到";
Blockly.Msg.VARIABLES_SET_TITLE ="賦值";
Blockly.Msg.VARIABLES_SET_TOOLTIP ="設定此變數,以使它和輸入值相等。";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
//luokailiang
Blockly.LKL_DECLARE='聲明';
Blockly.LKL_AS='為';
Blockly.LKL_VALUE='並賦值';
Blockly.LKL_VALUE2='賦值為';
Blockly.LKL_MAP='映射';
Blockly.LKL_MAP_FROM="從[";
Blockly.LKL_MAP_TO="]到[";
Blockly.LKL_MILLIS='毫秒';
Blockly.LKL_DELAY='延時';
Blockly.LKL_ATTACHINTERRUPT_PIN='中斷管脚#';
Blockly.LKL_DETACHINTERRUPT_PIN='取消中斷管脚#';
Blockly.LKL_MODE='模式';
Blockly.LKL_DO='執行';
Blockly.LKL_BUILDIN_LED='內嵌LED燈';
Blockly.LKL_STAT='設為';
Blockly.LKL_DIGITALWRITE_PIN='數位輸出管脚#';
Blockly.LKL_DIGITALREAD_PIN='數位輸入管脚#';
Blockly.LKL_ANALOGWRITE_PIN='類比輸出管脚#';
Blockly.LKL_ANALOGREAD_PIN='類比輸入管脚#';
Blockly.LKL_SERIAL_PRINT='打印';
Blockly.LKL_SERIAL_PRINTLN='打印（自動換行）';
Blockly.LKL_SERIAL_PRINT_HEX='打印（16進制/自動換行）';
Blockly.LKL_STEP='步長為';
Blockly.LKL_TONE_PIN='播放聲音管脚#';
Blockly.LKL_FREQUENCY='頻率';
Blockly.LKL_DURATION='持續時間';
Blockly.LKL_NOTONE_PIN='結束聲音管脚#';
Blockly.LKL_END_ADDITION='中）';
Blockly.LKL_BLOCKGROUP_CATEGORY='模塊組';
Blockly.LKL_IR_RECEIVE='紅外接收 管腳#';
Blockly.LKL_IR_RECEIVE_ENABLE='紅外接收使能 管腳#';
Blockly.LKL_IR_SEND_NEC1='紅外發射（';
Blockly.LKL_IR_SEND_NEC2='）管脚#';
Blockly.LKL_IR_RECEIVE_RAW='紅外接收並列印數據（RAW）管腳#';
Blockly.LKL_IR_SEND_RAW='紅外發射（RAW）管脚#';
Blockly.LANG_MATH_TO_INT='取整';
Blockly.LKL_SERVO='舵機';
Blockly.LKL_PIN='管脚#';
Blockly.LKL_DEGREE_0_180='角度（0~180）';
Blockly.LKL_READ_DEGREES='讀取度數';
Blockly.LKL_HIGH='高';
Blockly.LKL_LOW='低';
Blockly.LKL_ON='開';
Blockly.LKL_OFF='關';
Blockly.LKL_RISING='上升';
Blockly.LKL_FALLING='下降';
Blockly.LKL_CHANGE='改變';
Blockly.LKL_I2C_MASTER_WRITE="I2C寫入設備地址";
Blockly.LKL_I2C_MASTER_READ="I2C讀取設備地址";
Blockly.LKL_I2C_MASTER_READ2="I2C讀取";
Blockly.LKL_I2C_VALUE="值";
Blockly.LKL_I2C_BYTES="位元組數";
Blockly.LKL_I2C_AVAILABLE='讀取I2C成功嗎？';
Blockly.LANG_CONTROLS_FOR_INPUT_WITH = '按次';
Blockly.LANG_CONTROLS_FOR_INPUT_VAR = 'x';
Blockly.LANG_CONTROLS_FOR_INPUT_FROM = '從';
Blockly.LANG_CONTROLS_FOR_INPUT_TO = '到';
Blockly.LANG_CONTROLS_FOR_INPUT_DO = '執行';
Blockly.LANG_CONTROLS_WHILEUNTIL_TITLE_REPEAT = '重複';
Blockly.LANG_CONTROLS_WHILEUNTIL_INPUT_DO = '執行';
Blockly.LANG_CONTROLS_WHILEUNTIL_OPERATOR_WHILE = '滿足條件';
Blockly.LANG_CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = '不滿足條件';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_INPUT_OFLOOP = '迴圈';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = '跳出';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = '跳到下一個';
Blockly.LANG_CONTROLS_FLOW_STATEMENTS_WARNING = '警告：\n' +
'這個模塊只能\n' +
'用在迴圈中。';
Blockly.LANG_MATH_INT = '整數';
Blockly.LANG_MATH_LONG = '整數';
Blockly.LANG_MATH_FLOAT = '小數';
Blockly.LANG_MATH_BOOLEAN = '布林';
Blockly.LANG_MATH_CHAR = '字符';
Blockly.LANG_MATH_STRING = '字符串';
Blockly.LANG_LISTS_GET_INDEX_INPUT_AT = '獲取第';
Blockly.LANG_LISTS_GET_INDEX_INPUT_IN_LIST = '項（在數組';
Blockly.LANG_LISTS_GET_INDEX_TOOLTIP = '返回數組中指定位置的值。';
Blockly.LANG_LISTS_SET_INDEX_INPUT_AT = '設定第';
Blockly.LANG_LISTS_SET_INDEX_INPUT_IN_LIST = '項（在數組';
Blockly.LANG_LISTS_SET_INDEX_INPUT_TO = '中）為';
Blockly.LANG_LISTS_SET_INDEX_TOOLTIP = '設定數組中指定位置的值。';
Blockly.LANG_MATH_CONSTRAIN_INPUT_CONSTRAIN = '約束';
Blockly.LANG_MATH_CONSTRAIN_INPUT_LOW = '介於（最小值）';
Blockly.LANG_MATH_CONSTRAIN_INPUT_HIGH = '和（最大值）';
Blockly.LANG_MATH_RANDOM_INT_INPUT_FROM = '亂數從';
Blockly.LANG_MATH_RANDOM_INT_INPUT_TO = '到';
Blockly.LKL_DF_LED=' LED燈';
Blockly.LKL_DF_BUZZER='蜂鳴器';
Blockly.LKL_DF_BTN='按鈕（數位）';
Blockly.LKL_DF_VIBRATION='震動（數位）';
Blockly.LKL_DF_TILT='傾斜（數位）';
Blockly.LKL_DF_TOUCH='觸摸（數位）';
Blockly.LKL_DF_MAGNETIC='磁感應（數位）';
Blockly.LKL_DF_PYROELECTRIC_INFRARED='熱釋電紅外（數位）';
Blockly.LKL_MB_PYROELECTRIC_INFRARED='人體紅外';
Blockly.LKL_DF_JOYSTICK_D='搖杆-按鈕（數位）';
Blockly.LKL_DF_JOYSTICK_A='搖杆（類比）';
Blockly.LKL_JOYSTICK='搖杆';
Blockly.LKL_DF_POTENTIOMETER='電位器（類比）';
Blockly.LKL_POTENTIOMETER='電位器';
Blockly.LKL_DF_ROTATION='角度（類比）';
Blockly.LKL_DF_VOLTAGE='電壓（類比）';
Blockly.LKL_DF_PIEZO_DISK_VIRBRATION='壓電陶瓷震動（類比）';
Blockly.LKL_DF_SOUND='聲音（類比）';
Blockly.LKL_SOUND='聲音';
Blockly.LKL_DF_RELAY='繼電器';
Blockly.LKL_DF_LIGHT='光線（類比）';
Blockly.LKL_DF_GRAYSCALE='灰度（類比）';
Blockly.LKL_DF_FLAME='火焰（類比）';
Blockly.LKL_DF_TEMPERATURE='溫度（類比）';
Blockly.LKL_TEMPERATURE='溫度（℃）';
Blockly.LKL_DF_ACCELEROMETER='三軸加速度（類比）';
Blockly.LKL_DF_MOISTURE='土壤濕度（類比）';
Blockly.LKL_DF_WATER='水分（類比）';
Blockly.LKL_DF_CO='一氧化碳（類比）';
Blockly.LKL_DF_SHARP_GP2Y0A21='夏普GP2Y0A21紅外測距（類比）';
Blockly.LKL_MAKELISTFROM='從字串';
Blockly.LKL_SPLITBYDOU='創建數組';
Blockly.LKL_SETUP='初始化';
Blockly.LKL_WARNING_INTERRUPT='該管脚號不能作為中斷';
Blockly.LKL_CHAOSHENGBO='超聲波測距（cm）';
Blockly.LKL_MB_CHAOSHENGBO='超聲波測距';
Blockly.LKL_IR_RECEIVE_YES='有訊號';
Blockly.LKL_IR_RECEIVE_NO='無訊號';
Blockly.LANG_VARIABLES_SET_TITLE='賦值為';
Blockly.LKL_TEXT_JOIN='連接';
Blockly.LKL_SERIAL_AVAILABLE='有數據可讀嗎？';
Blockly.LKL_SERIAL_READSTR='讀取字符串';
Blockly.LKL_SERIAL_READ='讀取';
Blockly.LKL_IR_RECIEVE_TOOLTIP='在接收到紅外訊號時進行用戶自定義的處理。';
Blockly.LKL_IR_SEND_NEC_TOOLTIP='發射指定類型的紅外數據';
Blockly.LKL_IR_RECIEVE_RAW_TOOLTIP='在接收到紅外訊號時以RAW格式列印出紅外數據。';
Blockly.LKL_IR_SEND_RAW_TOOLTIP='發射RAW紅外數據,4個參數分別是管脚號、數組、數組長度、紅外訊號頻率';
Blockly.LKL_LIST_NAME='數組';
Blockly.LKL_LIST_LENGTH='數組長度';
Blockly.LKL_TO_INT='轉整數';
Blockly.LKL_TO_FLOAT='轉小數';
Blockly.LKL_DATA="數值";
Blockly.LKL_BITS="比特數";
Blockly.LKL_MB_LIGHT_GRAYSCALE='光線與灰度感測器';
Blockly.LKL_MB_LIGHT_GRAYSCALE_LED=' LED設為';
Blockly.LKL_MB_LIGHT_MOTOR='設定電機';
Blockly.LKL_MB_LIGHT_MOTOR_SPEED='轉速為（-255~255）';
Blockly.LKL_DELAY_MS='毫秒';
Blockly.LKL_DELAY_US='微秒';
Blockly.LKL_DHT11='DHT11管脚#';
Blockly.LKL_DHT11_T='獲取溫度';
Blockly.LKL_DHT11_H='獲取濕度';
Blockly.LKL_LCD_RGB_BACKLIGHT='液晶RGB背光屏';
Blockly.LKL_DF_LCD='液晶顯示幕';
Blockly.LKL_LCD_PRINT1='列印第1行';
Blockly.LKL_LCD_PRINT2='列印第2行';
Blockly.LKL_LCD_ROW='在第';
Blockly.LKL_LCD_COLUMN='行第';
Blockly.LKL_LCD_PRINT='列打印';
Blockly.LKL_LCD_SETCOLOR='設定顏色';
Blockly.LKL_LCD_STAT_ON='開';
Blockly.LKL_LCD_STAT_OFF='關';
Blockly.LKL_LCD_STAT_CURSOR='有光標';
Blockly.LKL_LCD_STAT_NOCURSOR='無光標';
Blockly.LKL_LCD_STAT_BLINK='閃爍';
Blockly.LKL_LCD_STAT_NOBLINK='不閃爍';
Blockly.LKL_LCD_STAT_CLEAR='清屏';
Blockly.LKL_7S_DISPLAY='7段數碼管';
Blockly.LKL_NUMBER='數位';
Blockly.LKL_BLUETOOTH='藍牙';
Blockly.LKL_BLUETOOTH_READ_STR='讀取數據（返回字串）';
Blockly.LKL_AVAILABLE='有數據可讀？';
Blockly.LKL_DATAPIN='數據管脚#';
Blockly.LKL_CLOCKPIN='時鐘管脚#';
Blockly.LKL_BITORDER='順序';
Blockly.LKL_MSBFIRST='高位先入';
Blockly.LKL_LSBFIRST='低位先入';
Blockly.LKL_TOSTRING='轉字串';
Blockly.LKL_ROMEO_MOTOR='Romeo電機';
Blockly.LKL_ROMEO_MOTOR_SPEED='轉速';
Blockly.LKL_STOP='停止';
Blockly.LKL_PULSEIN='脈衝長度（微秒）管脚#';
Blockly.LKL_PULSEIN_STAT='狀態';
Blockly.LKL_PULSEIN_TIMEOUT='超時（微秒）';
Blockly.LKL_SERIAL_READ_INT='整數';
Blockly.LKL_SERIAL_READ_FLOAT='小數';
Blockly.LKL_MAX='取最大值';
Blockly.LKL_MIN='取最小值';
Blockly.LKL_WRITE_SD_FILE='寫入SD檔案';
Blockly.LKL_SD_DATA='數據';
Blockly.LKL_SD_NEWLINE='換行';
Blockly.LKL_EEPROM_WRITE_LONG='寫入EEPROM地址';
Blockly.LKL_EEPROM_READ_LONG='讀取EEPROM地址';
Blockly.LKL_SENSE_MOTOR='設定馬達轉速為（-255~255）';
Blockly.LKL_SENSE_MOTOR_STOP='停止馬達';
Blockly.LKL_SENSE_SERVO='設定舵機角度';
Blockly.LKL_SENSE_RGBLED='設定RGB燈的顏色為';
Blockly.LKL_TRAFFIC_LED='設定交通燈';
Blockly.LKL_EAST='東';
Blockly.LKL_SOUTH='南';
Blockly.LKL_WEST='西';
Blockly.LKL_NORTH='北';
Blockly.LKL_SENSE_BUZZER='設定蜂鳴器為';
Blockly.LKL_SENSE_ULTRASONIC='超聲波感測器的值';
Blockly.LKL_SENSE_PYROELECTRIC_INFRARED='人體紅外感測器被觸發？';
Blockly.LKL_BUTTON='按鈕';
Blockly.LKL_UP='上';
Blockly.LKL_DOWN='下';
Blockly.LKL_LEFT='左';
Blockly.LKL_RIGHT='右';
Blockly.LKL_MID='中';
Blockly.LKL_IS_PRESSED='被按下？';
Blockly.LKL_SENSE_SLIDING='滑杆感測器的值';
Blockly.LKL_SENSE_TEMPERATURE='溫度感測器的值';
Blockly.LKL_SENSE_HUMIDITY='濕度感測器的值';
Blockly.LKL_SENSE_SOUND='聲音感測器的值';
Blockly.LKL_SENSE_LIGHT='光線感測器的值';
Blockly.LKL_SENSE_WEIGHT='稱重感測器的值';
Blockly.LKL_SENSE_IR='接收到紅外訊號值：';
Blockly.LKL_SENSE_DIGITAL_DISPLAY='設定LED數碼管的值（0~99）';
Blockly.LKL_SENSE_DIGITAL_DISPLAY_CLOSE='關閉LED數碼管';
Blockly.LKL_SENSE_LED_MATRIX='設定LED點陣的值（0~9）';
Blockly.LKL_SENSE_LED_MATRIX_CLOSE='關閉LED點陣';
Blockly.LANG_INOUT_DIGITAL_WRITE_TOOLTIP='設定指定管脚電平值';
Blockly.LKL_FORWARD='前進';
Blockly.LKL_BACKWARD='後退';
Blockly.LKL_TURNLEFT='左轉';
Blockly.LKL_TURNRIGHT='右轉';
Blockly.LKL_MBOT_SPEED='速度為（-255~255）';
Blockly.LKL_RUNTIME='系統運行時間';
Blockly.LKL_LED_ON_BOARD='板載';
Blockly.LKL_ALL='全部';
Blockly.LKL_SET_LED='設定LED';
Blockly.LKL_MBOT_TONE='播放聲音';
Blockly.LKL_MBOT_NOTONE='結束聲音';
Blockly.LKL_SHOW_FACE='表情面板';
Blockly.LKL_SHOW_FACE_TEXT='顯示文字：';
Blockly.LKL_SHOW_FACE_TIME='顯示時間';
Blockly.LKL_MBOT_SET_DISPLAY='設定數碼管';
Blockly.LKL_MBOT_SET_LIGHT='設定光線感測器';
Blockly.LKL_MBOT_SET_LIGHT_LED='LED狀態為';
Blockly.LKL_MBOT_SET_CAMERA='設定相機快門';
Blockly.LKL_MBOT_SET_CAMERA_STAT='狀態為';
Blockly.LKL_MBOT_SET_CAMERA_PRESS='按下快門';
Blockly.LKL_MBOT_SET_CAMERA_RELEASE='鬆開快門';
Blockly.LKL_MBOT_SET_CAMERA_FOCUS_ON='開始對焦';
Blockly.LKL_MBOT_SET_CAMERA_FOCUS_OFF='停止對焦';
Blockly.LKL_MBOT_LIGHT_SENSOR='光線感測器';
Blockly.LKL_LIGHT_SENSOR_ON_BOARD='板載';
Blockly.LKL_MBOT_BUTTON='按鈕';
Blockly.LKL_MBOT_BUTTON_PRESSED='已按下';
Blockly.LKL_MBOT_BUTTON_RELEASED='已鬆開';
Blockly.LKL_MBOT_LINE_FOLLOWER='巡線感測器';
Blockly.LKL_MBOT_JOYSTICK='搖杆';
Blockly.LKL_MBOT_JOYSTICK_X='X軸';
Blockly.LKL_MBOT_JOYSTICK_Y='Y軸';
Blockly.LKL_MBOT_POTENTIOMETER='電位器';
Blockly.LKL_MBOT_SOUND_SENSOR='音量感測器';
Blockly.LKL_MBOT_LIMIT_SWITCH='限位元開關';
Blockly.LKL_MBOT_TEMPERATURE='當前溫度';
Blockly.LKL_MBOT_PIR_MOTION_SENSOR='人體紅外感測器';
Blockly.LKL_MBOT_IR_REMOTE='紅外遙控器按下';
Blockly.LKL_MBOT_IR_REMOTE_PRESSED='鍵';
Blockly.LKL_SETTING='設定';
Blockly.LKL_SEND_MBOT_MESSAGE='發送mBot消息';
Blockly.LKL_MBOT_MESSAGE_RECEIVED='接收到的mBot消息';
Blockly.LKL_LABPLUS_ROBOT_MOVEMENT='設定機器人移動模式為';
Blockly.LKL_LABPLUS_ROBOT_MOVEMENT_GO_FORWARD='前進';
Blockly.LKL_LABPLUS_ROBOT_MOVEMENT_STOP='停止';
Blockly.LKL_LABPLUS_ROBOT_MOVEMENT_GO_BACK='後退';
Blockly.LKL_LABPLUS_ROBOT='設定機器人';
Blockly.LKL_LABPLUS_ROBOT_TURN_LEFT='左轉';
Blockly.LKL_LABPLUS_ROBOT_TURN_RIGHT='右轉';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY='設定螢幕顯示為';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_SMILE='微笑';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_NOSMILE='悲傷';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_CLOSE_EYE='閉眼';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_LEFT='左箭頭';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_RIGHT='右箭頭';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_TIAOWEN='條紋';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_ZEBRA='斑馬紋';
Blockly.LKL_LABPLUS_ROBOT_DISPLAY_NOTHING='黑屏';
Blockly.LKL_LABPLUS_ROBOT_LED_TOP='設定頂燈為';
Blockly.LKL_LABPLUS_ROBOT_LED_SIDE='設定側燈顏色為';
Blockly.LKL_LCD_ADDRESS="液晶顯示屏 設備地址";
var MSG = {
catInOut:"輸入/輸出",
catControl:"控制",
catMath:"數學",
catText:"文字",
catLists:"數組",
catLogic:"邏輯",
catGroup:"通信",
catStorage:"存儲",
catSensor:"感測器",
catActuator:"執行器",
catVar:"變數",
catFun:"函數",
catEthernet:"以太網",
catEthernet_init:"初始化",
catEthernet_clinet:"客戶端",
catSense:"盛思（盒子）",
catSense2:"盛思（機器人）",
catLuxe:"濼喜機器人",
tab_blocks:"模塊",
tab_arduino:"程式碼"
};
Blockly.LKL_TOOLTIP_INOUT_HIGHLOW='返回高電平或低電平';
Blockly.LKL_TOOLTIP_INOUT_DIGITAL_READ='返回指定管脚的電平值';
Blockly.LKL_TOOLTIP_INOUT_ANALOG_WRITE='設定指定管脚的值（0~255）';
Blockly.LKL_TOOLTIP_INOUT_ANALOG_READ='返回指定管脚的值（0~1024）';
Blockly.LKL_TOOLTIP_INOUT_ATTACHINTERRUPT='設定指定管脚的中斷';
Blockly.LKL_TOOLTIP_INOUT_DETACHINTERRUPT='取消指定管脚的中斷';
Blockly.LKL_TOOLTIP_CONTROL_SETUP='初始化操作（這裡面的內容只執行一次）';
Blockly.LKL_TOOLTIP_CONTROL_DELAY='延遲指定時間';
Blockly.LKL_TOOLTIP_CONTROL_MILLIS='返回系統運行的時間';
Blockly.LKL_TOOLTIP_VARIABLES_DECLARE='聲明並初始化一個變數';
Blockly.LKL_TOOLTIP_MATH_MAX='返回2個數中較大的那個';
Blockly.LKL_TOOLTIP_MATH_MIN='返回2個數中較小的那個';
Blockly.LKL_TOOLTIP_MATH_MAP='將一個數從第一個區間映射到第二個區間,並返回映射之後的值。';
Blockly.LKL_TOOLTIP_TEXT_JOIN='將2個字串拼接成一個字串。';
Blockly.LKL_TOOLTIP_TEXT_TOTEXT='將一個數位轉為一個字串。';
Blockly.LKL_TOOLTIP_TEXT_TOINT='將一個字串轉為一個整數。';
Blockly.LKL_TOOLTIP_TEXT_TOFLOAT='將一個字串轉為一個小數。';
Blockly.LKL_TOOLTIP_LISTS_CREATE_WITH_TEXT='通過一個字串來創建一個數組。';
Blockly.LKL_TOOLTIP_LOGIT_TRUEORFALSE='如果第一個數為真,則返回第二個數,否則返回第三個數。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_SERIAL_AVAILABLE='如果串口有數據可讀,返回真,否則返回假。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_SERIAL_READ_STR='返回串口中的字串。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_SERIAL_READ_INT='返回串口中的整數。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_SERIAL_READ_FLOAT='返回串口中的小數。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_CHAOSHENGBO='返回超聲波感測器測得的距離。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_DHT11_TEM='返回溫濕度感測器測得的溫度。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_DHT11_HUM='返回溫濕度感測器測得的濕度。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_SERVO_MOVE = '在0~180°間旋轉。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_SERVO_READ = '返回舵機當前停留的角度。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_TONE = '按指定的頻率播放聲音。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_TONE2 = '按指定的頻率和持續時間播放聲音。';
Blockly.LKL_TOOLTIP_BLOCKGROUP_NOTONE = '停止播放聲音。';
Blockly.LUXE_LED='燈#';
Blockly.LUXE_MOTOR='電機#';
Blockly.LUXE_STAT='為';
Blockly.LUXE_SPEED='速度為';
Blockly.LUXE_DIR='方向為';
Blockly.LUXE_LED_ON='亮';
Blockly.LUXE_LED_OFF='滅';
Blockly.LUXE_MOTOR_FORWARD='順時針';
Blockly.LUXE_MOTOR_REVERSE='逆時針';
Blockly.LUXE_LED_CHANGE='轉換狀態';
Blockly.LUXE_MOTOR_CHANGE='改變方向';
Blockly.LUXE_MOTOR_STOP='停止';
Blockly.LUXE_SPEAKER_PLAYSOUND='播放聲音';
Blockly.LUXE_SPEANER_NOSOUND='停止播放聲音';
Blockly.LUXE_SPEAKER_FREQUENCY='頻率';
Blockly.LUXE_SPEAKER_DURATION='持續時間';

//-----------------NOVA---------------------------------
Blockly.LKL_NOVA_PORT = '端口';
Blockly.LKL_NOVA_STAT = '設為';
Blockly.LKL_NOVA_GET_STAT = '獲取';

// LED
Blockly.LKL_NOVA_LED = 'LED燈';
Blockly.LKL_NOVA_LED_ON = '開';
Blockly.LKL_NOVA_LED_OFF = '關';

// Button
Blockly.LKL_NOVA_BUTTON_PRESSED = '按下';
Blockly.LKL_NOVA_BUTTON_RELEASED = '鬆開';
Blockly.LKL_NOVA_BTN = '按鈕';
Blockly.LKL_NOVA_ABCD = '#';

Blockly.LKL_NOVA_TILTSWITCH = '傾斜開關';
Blockly.LKL_NOVA_SOUND = '聲音傳感器'; 
Blockly.LKL_NOVA_LIMISWICTH = '限位開關'; 
Blockly.LKL_NOVA_LIGHT = '光敏'; 

Blockly.LKL_NOVA_BUZZER = '蜂鳴器'; 
Blockly.LKL_NOVA_FREQUENCY = '頻率(Hz)'; 
Blockly.LKL_NOVA_LKL_DURATION = '持續時間(ms)'; 

Blockly.LKL_NOVA_MOTOR = '直流電機'; 
Blockly.LKL_NOVA_MOTOR_SPEED = '轉速(-100~100)%'; 

Blockly.LKL_NOVA_ULTRASONIC = '超聲波測距(cm)'; 

Blockly.LKL_NOVA_DHT11 = '溫濕度';
Blockly.LKL_NOVA_TYPE = '類型';
Blockly.LKL_NOVA_DHT11_H = '獲取濕度';
Blockly.LKL_NOVA_DHT11_T = '獲取溫度';

Blockly.LKL_NOVA_SERVO = '舵機';
Blockly.LKL_NOVA_DEGREE_0_180 = '角度（0~180）';
Blockly.LKL_NOVA_DELAY = '延時';
Blockly.LKL_NOVA_DELAY_MS = '毫秒';

Blockly.LKL_NOVA_LINEFINDER = '巡線';
Blockly.LKL_NOVA_L = '左邊狀態';
Blockly.LKL_NOVA_R = '右邊狀態';
Blockly.LKL_NOVA_READ = '獲取黑白線狀態';

Blockly.LKL_NOVA_4DIGITDISPLAY = '數碼管';
Blockly.LKL_NOVA_NUMBER = '顯示數字';
Blockly.LKL_NOVA_DISPLAY_HOUR= '顯示小時';
Blockly.LKL_NOVA_DISPLAY_MIN = '顯示分鐘';

Blockly.LKL_NOVA_RTC = '時鐘';
Blockly.LKL_NOVA_RTC_SEC = '秒';
Blockly.LKL_NOVA_RTC_MIN = '分';
Blockly.LKL_NOVA_RTC_HOUR = '時';
Blockly.LKL_NOVA_RTC_WEEK = '星期';
Blockly.LKL_NOVA_RTC_DAY = '日';
Blockly.LKL_NOVA_RTC_MON = '月';
Blockly.LKL_NOVA_RTC_YEAR = '年';

Blockly.LKL_NOVA_IR_REC = '紅外接收';

Blockly.LKL_NOVA_BLUETOOTH = '藍牙';
Blockly.LKL_NOVA_BLUETOOTH_AVAILABLE = '有數據可讀？';
Blockly.LKL_NOVA_BLUETOOTH_READ_STR = '讀取數據（返回字符串）';
Blockly.LKL_NOVA_BLUETOOTH_READ_NUM = '讀取數據（返回數字）';

//spi
Blockly.TO_SPI_SLAVE_PIN='向SPI從機#';
Blockly.SPI_TRANSFER='傳輸';

Blockly.LKL_SERIAL_BEGIN='波特率';

//stepper
Blockly.LKL_STEPPER='步進電機';
Blockly.LKL_STEPPER_SETUP_STEPPER='初始化步進電機';
Blockly.LKL_STEPPER_PIN1='管腳1#';
Blockly.LKL_STEPPER_PIN2='管腳2#';
Blockly.LKL_STEPPER_PIN3='管腳3#';
Blockly.LKL_STEPPER_PIN4='管腳4#';
Blockly.LKL_STEPSPERREVOLUTION='每轉步數';
Blockly.LKL_STEPPER_SET_SPEED='設置轉速';
Blockly.LKL_STEPPER_STEP='移動步數';

//-----------------Ethernet------------------------------------
Blockly.CATA
Blockly.MIXLY_ETHERNET_BEGIN='初始化 (DHCP)';
Blockly.MIXLY_ETHERNET='以太網';
Blockly.MIXLY_ETHERNET2='以太網2';
Blockly.MIXLY_ETHERNET_MAC_ADDRESS='Mac地址';
Blockly.MIXLY_ETHERNET_LOCALIP='本地IP';
Blockly.MIXLY_ETHERNET_CLINET_CONNECT_SERVER='客戶端連接到服務器';
Blockly.MIXLY_ETHERNET_CLINET_PORT='端口';
Blockly.MIXLY_ETHERNET_CLINET_STOP='客戶端-停止';
Blockly.MIXLY_ETHERNET_CLINET_CONNECTED='客戶端-已連接';
Blockly.MIXLY_ETHERNET_CLINET_AVAILABLE='客戶端-有數據可讀';
Blockly.MIXLY_ETHERNET_CLINET_PRINT='客戶端-打印';
Blockly.MIXLY_ETHERNET_CLINET_PRINTLN='客戶端-打印（自動換行）';
Blockly.MIXLY_ETHERNET_CLINET_READ='客戶端-讀取';
Blockly.MIXLY_ETHERNET_CLINET_GET_REQUEST='GET請求';
Blockly.MIXLY_ETHERNET_CLINET_URL='URL';
Blockly.MIXLY_ETHERNET_CLINET_SERVER='服務器';

//DS18B20温度传感器
Blockly.MIXLY_DS18B20='DS18B20 管腳#';
Blockly.MIXLY_DS18B20_GET_TEMP='獲取溫度';
Blockly.MIXLY_DS18B20_C='°C';
Blockly.MIXLY_DS18B20_F='°F';

//GPS
Blockly.MIXLY_GPS_INIT='GPS初始化';
Blockly.MIXLY_GPS_DATA_AVAILABLE='GPS獲取到數據';
Blockly.MIXLY_GPS_DATA_ENCODE='GPS解析數據成功';
Blockly.MIXLY_GPS_LOCATION='位置';
Blockly.MIXLY_GPS_DATE='日期';
Blockly.MIXLY_GPS_TIME='時間';
Blockly.MIXLY_GPS_ISVALID='有效';
Blockly.MIXLY_GPS_GET='GPS獲取';
Blockly.MIXLY_GPS_LOCATION_LAT='位置-緯度';
Blockly.MIXLY_GPS_LOCATION_LNG='位置-經度';
Blockly.MIXLY_GPS_DATE_YEAR='日期-年';
Blockly.MIXLY_GPS_DATE_MONTH='日期-月';
Blockly.MIXLY_GPS_DATE_DAY='日期-日';
Blockly.MIXLY_GPS_TIME_HOUR='時間-時';
Blockly.MIXLY_GPS_TIME_MINUTE='時間-分';
Blockly.MIXLY_GPS_TIME_SECOND='時間-秒';
Blockly.MIXLY_GPS_TIME_CENTISECOND='時間-厘秒';

//factory
Blockly.MIXLY_PARAMS = '參數';

//others
Blockly.LKL_WARNING_NOT_DECLARE='該變量未聲明';